"""
build_vtiger_file.py
====================
Takes a list of companies + per-company enrichment dicts and writes the final
Vtiger-ready files (XLSX + comma-CSV + coverage report).

This script runs in Claude.ai's analysis tool (Python sandbox). It uses only
pandas and openpyxl — both pre-installed. Web enrichment is done by Claude
BEFORE calling this script (via WebSearch / WebFetch); this script just formats.

USAGE (from within a Claude analysis tool block):
    from build_vtiger_file import build_files

    companies = [
        {"EnterpriseName": "ACME LIMITED", "Address": "...", "State": "...",
         "District": "MUMBAI", "Pincode": "400001"},
        ...
    ]
    enrichment = {
        "ACME LIMITED": {
            "first": "Anil", "last": "Kumar", "designation": "CIO",
            "email": "anil@acme.com", "phone": "022-12345678", "mobile": "",
            "website": "https://acme.com", "linkedin": "https://linkedin.com/in/anilkumar",
            "source_url": "https://www.zaubacorp.com/company/ACME-LIMITED",
            "confidence": "High", "cin": "L12345MH2000PLC123456",
            "notes": "Verified via company press release",
        },
        ...
    }
    paths = build_files(companies, enrichment, output_dir="/mnt/user-data/outputs")
    # Returns: {"xlsx": "...", "csv": "...", "report": "..."}
"""
import csv
import os
import re
from datetime import date
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font

# ----- 75-column Vtiger schema (exact order) -----
VTIGER_HEADERS = [
    'Lead ID','Company','Salutation','First Name','Last Name','Primary Email',
    'Designation','Location','Industry','Lead Generated on','Lead Generated By',
    'Lead Source','Lead Sub-Status','Lead Status','Office Phone','Created By',
    'Website','Mobile Phone','No. of Branches','Annual Revenue','Last Follow-up On',
    'Number of Employees','Created Time','Next follow-up on','Network Budget',
    'Modified Time','Requirement','Estimated Order Value','CreatedByExt',
    'Assigned To','ModifiedByExt','Record Currency','Last Modified By',
    'Record Conversion Rate','Source Campaign','Last Contacted Via',
    'Reason for Enquiry Lost','Request count','Lead Handled by',
    'Email Confirmation Last requested on','Email Opt-in','IT Users',
    'Primary Phone Field','Primary Email Field','Is closed?','Source',
    'Twitter Username','Engagement Score','Language','Timezone',
    'Facebook Lead ID','Ad Group','SMS opt-in','Fax','Platform','Country',
    'Street','PO Box','Postal Code','City','State','Latitude','Longitude',
    'Additional Details','Lead Image','Consent requested','Data erasure request',
    'Erased','Stop processing request','Track my email engagement',
    'Track my document engagement','Consent Last Requested Time','Facebook Id',
    'Instagram Id','Twitter Id',
]

CITY_FIXES = {
    'NAVI MUMBAI': 'Navi Mumbai', 'MUMBAI CITY': 'Mumbai',
    'KALYAN EAST': 'Kalyan', 'KALYAN': 'Kalyan',
    'BYCULLA': 'Byculla', 'TITWALA': 'Titwala',
    'PUNE': 'Pune', 'MUMBAI': 'Mumbai', 'THANE': 'Thane',
    'PAWANE': 'Navi Mumbai', 'WORLI': 'Mumbai',
    'VIKHROLI': 'Mumbai', 'BELAPUR': 'Navi Mumbai',
}

COMMON_FEMALE = {
    'priya','neha','pooja','reema','riya','asha','sneha','meera','radha',
    'sunita','geeta','seema','anita','kavita','smita','rekha','shilpa',
    'swati','ritu','divya','jyoti','rashmi','suman','nisha','manisha',
    'kiran','deepa','preeti','rachna','vandana','aarti','pallavi',
}

# Industry inference from company-name keywords
INDUSTRY_KEYWORDS = [
    ('Financial Services', ['financial','finance','capital','securities','banking','investments','broking','asset','nidhi']),
    ('Oil & Gas',          ['oil','gas','petroleum','energy','natural gas']),
    ('Construction & Infra',['construction','builders','infra','realty','cement','steel','engineering','epc']),
    ('Logistics & Shipping',['logistics','shipping','transport','translogistics','transformers','cargo']),
    ('Pharmaceuticals',    ['pharma','pharmacle','laboratory','medical','healthcare','medicine','biosciences']),
    ('Manufacturing',      ['industries','manufactur','chemicals','emulsifiers','oils','fabric','plast']),
    ('IT & Software',      ['software','technology','tech ','systems','infotech','digital','innovations','edtech']),
    ('Travel & Hospitality',['travel','hospitality','tours','hotels']),
    ('Real Estate',        ['real estate','properties','estates','housing']),
    ('Agriculture',        ['agro','agri','shetkari','krishi','farming','agrovet']),
    ('Cooperative Society',['sahakari','patsantha','cooperative']),
]

def _city(d):
    if not d or pd.isna(d):
        return ''
    return CITY_FIXES.get(str(d).strip().upper(), str(d).strip().title())

def _normalize_phone(p):
    """Normalize Indian phone to +91-XX-XXXX-XXXX or +91-XXXXX-XXXXX (mobile)."""
    if not p: return ''
    p = str(p).strip()
    if not p or p.lower() == 'nan': return ''
    digits = re.sub(r'[^\d]', '', p)
    if digits.startswith('91') and len(digits) == 12:
        return f'+91-{digits[2:4]}-{digits[4:8]}-{digits[8:]}'
    if len(digits) == 11 and digits.startswith('0'):
        return f'+91-{digits[1:3]}-{digits[3:7]}-{digits[7:]}'
    if len(digits) == 10:
        return f'+91-{digits[:5]}-{digits[5:]}'
    if len(digits) == 12 and digits.startswith('91'):
        return f'+91-{digits[2:7]}-{digits[7:]}'
    return p  # leave unchanged if doesn't fit any known pattern

def _infer_industry(company):
    """Infer industry from explicit company-name keywords.
    Returns empty string if no keyword matches — NEVER guesses "Other / Diversified"
    (that was implying false certainty). Blank is honest.
    """
    cl = str(company or '').lower()
    for industry, kws in INDUSTRY_KEYWORDS:
        if any(k in cl for k in kws):
            return industry
    return ''  # honest — we don't know

def _clean_website(existing):
    """Sanitize the Website field. Returns the value only if it's a real URL.
    NEVER fabricates. If empty or invalid (e.g. email, phone), returns ''.
    """
    if not existing: return ''
    s = str(existing).strip()
    if not s or s.lower() == 'nan': return ''
    # Reject obvious non-URLs that leaked from bad source data
    if '@' in s:           return ''   # email in website column
    if re.match(r'^[\d\+\-\s()]+$', s): return ''  # phone number
    # Accept only if it looks like a URL or domain
    if s.startswith(('http://','https://','www.')) or re.match(r'^[\w-]+\.[\w-]+', s):
        return s
    return ''

def _salutation(first):
    f = (first or '').strip().lower()
    if not f: return ''
    if f in COMMON_FEMALE: return 'Ms.'
    # Heuristic: many Indian female names end in 'a' or 'i'
    if (f.endswith('a') or f.endswith('i')) and f not in {'krishna','vishnu','aditya','akash','manish','rajesh','suresh','ramesh','dinesh','prakash','ashish','satish','jatin'}:
        return 'Ms.'
    return 'Mr.'

def _map_designation(found, has_name=True):
    """Map free-text title to one of AIPL's 4 IT buckets or a clean Gatekeeper- bucket.
    Returns (designation, is_it_role, is_default_placeholder).
    """
    if not found:
        # If we have a name but no title, mark unknown gatekeeper. Otherwise placeholder.
        if has_name:
            return ('Gatekeeper - Unknown Role', False, False)
        return ('IT Manager / IT Head', False, True)
    f = found.strip()
    fl = f.lower()
    # Real IT roles
    if re.search(r'\b(cio|cto|ciso|chief\s+information\s+officer|chief\s+technology\s+officer|vp\s*-?\s*(it|tech|technology|information)|vice\s*president\s*-?\s*(it|tech|technology|information))\b', fl):
        return ('VP IT / CISO / CTO', True, False)
    if re.search(r'\b(it\s*infra|infrastructure\s*(head|manager|lead))\b', fl):
        return ('IT Infra / Sr. IT Infra', True, False)
    if re.search(r'\b(it\s*(procurement|purchase|purchasing)|procurement\s*head|purchase\s*head)\b', fl):
        return ('IT Procurement / Purchase', True, False)
    if re.search(r'\b(it\s*(head|manager|lead)|head\s*-?\s*it|head\s+of\s+(it|technology|digital)|manager\s*-?\s*it|sr\.?\s*vp\s*&?\s*cio|it\s+professional)\b', fl):
        return ('IT Manager / IT Head', True, False)
    # Garbage placeholders that crept in from prior runs
    if f in ('Care Of (Reg. Address)', 'Contact (role unspecified)', 'Head Office Contact'):
        return ('Gatekeeper - Unknown Role', False, False)
    # Clean Gatekeeper buckets (instead of 24 variants of "Chairman/Director/Founder")
    if 'chairman' in fl and ('md' in fl or 'managing' in fl):
        return ('Gatekeeper - Chairman & MD', False, False)
    if 'managing director' in fl or fl == 'md':
        return ('Gatekeeper - Managing Director', False, False)
    if 'chairman' in fl:
        return ('Gatekeeper - Chairman', False, False)
    if 'ceo' in fl:
        return ('Gatekeeper - CEO', False, False)
    if 'founder' in fl:
        return ('Gatekeeper - Founder', False, False)
    if 'designated partner' in fl or 'partner' in fl:
        return ('Gatekeeper - Partner', False, False)
    if 'director' in fl:
        return ('Gatekeeper - Director', False, False)
    # Last resort: keep verbatim under Gatekeeper prefix
    return (f'Gatekeeper - {f}', False, False)

def _build_row(src, enr):
    """Build one Vtiger row from a source company dict + enrichment dict."""
    row = {h: '' for h in VTIGER_HEADERS}

    # ---- Defaults (apply to every row) ----
    row['Lead Generated on']      = date.today().strftime('%d/%m/%Y')
    row['Lead Source']            = 'Master DB'
    row['Lead Sub-Status']        = 'Not Connected'
    row['Lead Status']            = 'Prospect'
    row['Record Currency']        = 'INR'
    row['Record Conversion Rate'] = '1'
    row['Request count']          = '0'
    row['Email Opt-in']           = 'singleoptinuser'
    row['SMS opt-in']             = 'singleoptinuser'
    row['Is closed?']             = 'No'
    row['Source']                 = 'IMPORT'
    row['Engagement Score']       = '0'
    row['Country']                = 'India'

    # ---- Source address fields ----
    row['Company'] = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
    row['Street']  = str(src.get('Address') or '').strip()
    pin = src.get('Pincode') or src.get('Postal Code') or ''
    if pin and not pd.isna(pin):
        row['Postal Code'] = str(int(pin)) if isinstance(pin, (int, float)) else str(pin).strip()
    row['City']    = _city(src.get('District') or src.get('City'))
    # Don't assume Maharashtra — leave blank if the file didn't provide a state.
    # (AIPL's files cover multiple states; defaulting would mislabel them.)
    _state = str(src.get('State') or '').strip()
    row['State']   = _state.title() if _state and _state.lower() != 'nan' else ''

    # ---- Enrichment fields ----
    enr = enr or {}
    fn = (enr.get('first') or '').strip()
    ln = (enr.get('last') or '').strip()
    has_name = bool(fn or ln)
    found_title = (enr.get('designation') or '').strip()
    mapped_title, is_it_role, is_default = _map_designation(found_title, has_name=has_name)

    # Salutation: only set if enrichment explicitly provided one (don't guess from name)
    row['Salutation']    = (enr.get('salutation') or '').strip()
    row['First Name']    = fn
    row['Last Name']     = ln
    row['Designation']   = mapped_title
    row['Primary Email'] = (enr.get('email') or '').strip()
    row['Office Phone']  = _normalize_phone(enr.get('phone'))
    row['Mobile Phone']  = _normalize_phone(enr.get('mobile'))
    row['Website']       = _clean_website(enr.get('website'))

    # ---- Auto-fill missing email via permutation + MX validation ----
    # Only fires when we have a name + a verified website but no email.
    # Pure Python, zero LLM calls, ~1 sec per company.
    if has_name and not row['Primary Email'] and row['Website']:
        try:
            from email_finder import find_email
            r = find_email(fn, ln, row['Website'])
            if r and r.get('email') and r.get('mx_ok'):
                row['Primary Email'] = r['email']
                # Stash provenance so the team knows this is MX-validated not verified
                enr = dict(enr)
                enr['notes'] = ((enr.get('notes') or '') +
                    f" | Email auto-derived: {r['method']}").strip(' |')
        except Exception:
            pass  # never fail the build over an enrichment helper

    # ---- Marketing-team defaults (so Vtiger doesn't require manual assign) ----
    row['Industry']        = _infer_industry(row['Company'])
    row['Lead Handled by'] = 'Marketing Team'
    row['Assigned To']     = 'Marketing Team'

    # ---- Additional Details: stash provenance ----
    details = []
    # Only flag if the title looked IT-like at first glance but didn't match an IT bucket
    # (mapped_title starts with "Gatekeeper -" already communicates the rest)
    if (fn or ln) and not is_it_role and found_title and not mapped_title.startswith('Gatekeeper'):
        details.append('ROLE FLAG: Not IT-specific — use as gatekeeper to reach IT decision-maker')
    cin = (enr.get('cin') or '').strip()
    linkedin = (enr.get('linkedin') or '').strip()
    source_url = (enr.get('source_url') or '').strip()
    confidence = (enr.get('confidence') or '').strip()
    notes = (enr.get('notes') or '').strip()
    if cin:        details.append(f'CIN: {cin}')
    if linkedin:   details.append(f'LinkedIn: {linkedin}')
    if source_url: details.append(f'Source: {source_url}')
    if confidence: details.append(f'Confidence: {confidence}')
    if notes:      details.append(f'Notes: {notes}')
    row['Additional Details'] = ' | '.join(details)
    return row

def _merge_cache_into_enrichment(companies, enrichment):
    """
    For each company, check the local SQLite cache. If we have a higher-confidence
    contact cached (from prior runs or team-verified), use it. Otherwise, when
    fresh enrichment is provided, save it back to the cache.

    This is the FLYWHEEL: every run improves future runs.
    """
    try:
        from local_cache import Cache
        cache = Cache()
    except Exception:
        return enrichment  # cache optional; never fail the build

    CONF_RANK = {'High': 0, 'Medium': 1, 'Low': 2, '': 3, None: 3}
    merged = dict(enrichment or {})

    # v7.2: re-verify cached emails via MX so we don't serve dead/wrong addresses
    try:
        from email_finder import _has_mx, _domain_from_website
        _can_verify = True
    except Exception:
        _can_verify = False

    def _email_still_valid(email):
        """Cheap MX re-check on a cached email. True if domain still accepts mail."""
        if not email or '@' not in email:
            return False
        if not _can_verify:
            return True  # can't check — assume ok rather than drop
        domain = email.split('@', 1)[1].strip().lower()
        try:
            return _has_mx(domain)
        except Exception:
            return True  # network hiccup — don't punish the cached data

    for src in companies:
        name = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
        if not name:
            continue
        hit = cache.lookup_company(name)
        fresh = merged.get(name, {}) or {}

        if hit and hit.get('best'):
            cached = hit['best']
            fresh_conf  = CONF_RANK.get((fresh.get('confidence') or '').title(), 3)
            cached_conf = CONF_RANK.get((cached.get('confidence') or '').title(), 3)
            is_stale    = cached.get('is_stale', False)
            days_old    = cached.get('days_old', 0)

            # ---- v7.2 RULE: FRESH RESEARCH ALWAYS WINS ----
            # Only fall back to cache for fields the fresh pass DIDN'T find.
            # Cache never overrides a value fresh research produced this run.
            cached_email = cached.get('email', '')
            # Re-verify cached email before serving it
            if cached_email and not _email_still_valid(cached_email):
                cached_email = ''  # drop dead email — don't serve it

            # Downgrade confidence on stale cache so the team knows to re-check
            if is_stale:
                cache_conf_label = 'Low'   # stale → never High
                stale_note = f"⚠ CACHED {days_old}d ago (STALE — re-verify before calling)"
            else:
                cache_conf_label = 'Medium' if cached.get('confidence') == 'High' else cached.get('confidence', 'Low')
                stale_note = f"Cached {days_old}d ago — verify before calling"

            merged[name] = {
                # Fresh value if present, else fall back to cache (fill-gaps only)
                'first':       fresh.get('first')       or cached.get('first_name', ''),
                'last':        fresh.get('last')        or cached.get('last_name', ''),
                'designation': fresh.get('designation') or cached.get('designation', ''),
                'email':       fresh.get('email')       or cached_email,
                'phone':       fresh.get('phone')       or cached.get('phone', ''),
                'mobile':      fresh.get('mobile')      or cached.get('mobile', ''),
                'website':     fresh.get('website')     or hit['company'].get('website', ''),
                'linkedin':    fresh.get('linkedin')    or cached.get('linkedin', ''),
                'source_url':  fresh.get('source_url')  or cached.get('source_url', ''),
                # Confidence = fresh's if fresh found a name; else downgraded cache label
                'confidence':  (fresh.get('confidence') if fresh.get('first') or fresh.get('last')
                                else cache_conf_label),
                'cin':         fresh.get('cin')         or hit['company'].get('cin', ''),
                'notes':       ((fresh.get('notes','') + ' | ' if fresh.get('notes') else '') +
                                (stale_note if not (fresh.get('first') or fresh.get('last')) else '')
                               ).strip(' |'),
            }

        # Save fresh enrichment back to cache for future runs (if we have a name)
        if fresh and (fresh.get('first') or fresh.get('last') or fresh.get('email')):
            cache.save_company(name,
                website=fresh.get('website',''),
                city=str(src.get('District') or src.get('City') or ''),
                state=str(src.get('State','')),
                address=str(src.get('Address','')),
                pincode=str(src.get('Pincode','')),
            )
            cache.save_contact(name, fresh)

    cache.close()
    return merged


def build_files(companies, enrichment, output_dir='/mnt/user-data/outputs', filename_base='Hygienic_Leads'):
    """
    Build all three output files.

    companies: list of dicts with at least EnterpriseName/Company + address fields
    enrichment: dict keyed by company name -> enrichment dict
                {first, last, designation, email, phone, mobile, website,
                 linkedin, source_url, confidence, cin, notes}
    output_dir: where to write the files (Claude analysis tool default works)
    filename_base: base filename (default "Hygienic_Leads")

    Returns dict of paths: {"xlsx", "csv", "report"}
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    xlsx_path = out_dir / f'{filename_base}.xlsx'
    csv_path  = out_dir / f'{filename_base}.csv'
    rpt_path  = out_dir / f'{filename_base}_Coverage_Report.txt'

    # ---- Cache flywheel: merge with prior verified contacts + save fresh ones ----
    enrichment = _merge_cache_into_enrichment(companies, enrichment)

    rows = []
    for src in companies:
        key = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
        enr = enrichment.get(key, {})
        rows.append(_build_row(src, enr))

    # ---- XLSX (for human review) ----
    wb = Workbook()
    ws = wb.active
    ws.title = 'Vtiger_Leads'
    ws.append(VTIGER_HEADERS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    for r in rows:
        ws.append([r[h] for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws.cell(row=1, column=ci).column_letter
        ws.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws.freeze_panes = 'A2'
    wb.save(xlsx_path)

    # ---- Comma-CSV (for Vtiger import) ----
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

    # ---- v6: Sales priority tagging (Hot/Warm/Cold) ----
    try:
        from sales_priority import score as _priority_score
        for r in rows:
            tier, reason = _priority_score(r)
            r['Source Campaign'] = tier  # stamp priority in Vtiger col
            # Append reason to Additional Details
            existing_ad = r.get('Additional Details', '')
            r['Additional Details'] = (
                (existing_ad + ' | ' if existing_ad else '') +
                f"Priority: {tier} ({reason})"
            ).strip(' |')
    except ImportError:
        pass  # v5 fallback — skill works without sales_priority

    # ---- v7: Pack action recommendation INTO the XLSX itself ----
    # Use the "Reason for Enquiry Lost" unused Vtiger field to store the
    # team's next-action per company. This way the XLSX is the single
    # source of truth — team can filter/sort by this column.
    for r in rows:
        cat, action = _classify_action(r)
        r['Reason for Enquiry Lost'] = cat  # filterable bucket name
        # Stash the human-readable action in Additional Details
        existing_ad = r.get('Additional Details', '')
        r['Additional Details'] = (
            (existing_ad + ' | ' if existing_ad else '') +
            f"Next Action: {action}"
        ).strip(' |')

    # Re-write XLSX + CSV with the priority stamps
    # (the xlsx/csv above were written WITHOUT Source Campaign — overwrite now)
    wb2 = Workbook()
    ws2 = wb2.active
    ws2.title = 'Vtiger_Leads'
    ws2.append(VTIGER_HEADERS)
    for cell in ws2[1]:
        cell.font = Font(bold=True)
    for r in rows:
        ws2.append([r.get(h, '') for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws2.cell(row=1, column=ci).column_letter
        ws2.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws2.freeze_panes = 'A2'
    wb2.save(xlsx_path)
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

    # ============================================================
    # v7: DEFAULT OUTPUT = XLSX + CSV ONLY
    # Everything else is opt-in via env vars (or kwargs). Keeps the
    # output lean — all the value packed into the two import-ready files.
    #
    # To enable extras, set ANY of:
    #   AIPL_GEN_COVERAGE_REPORT=1   → generate Coverage_Report.txt
    #   AIPL_GEN_PHONE_SCRIPTS=1     → generate Phone_Scripts.md
    #   AIPL_GEN_EMAIL_TEMPLATES=1   → generate Email_Templates.md
    #   AIPL_GEN_LEAD_BRIEFS=1       → generate Lead_Briefs.md
    #   AIPL_ENABLE_PAID_TOOLS=1     → generate Paid_Tool_Sheet.md
    # ============================================================
    result = {
        'xlsx': str(xlsx_path),
        'csv':  str(csv_path),
    }

    if os.environ.get('AIPL_GEN_COVERAGE_REPORT') == '1':
        _write_actionable_coverage_report(rows, rpt_path)
        result['report'] = str(rpt_path)

    if os.environ.get('AIPL_ENABLE_PAID_TOOLS') == '1':
        action_path = out_dir / f'{filename_base}_Paid_Tool_Sheet.md'
        _write_mode_b_action_sheet(rows, action_path)
        result['paid_tool_sheet'] = str(action_path)

    if os.environ.get('AIPL_GEN_PHONE_SCRIPTS') == '1':
        try:
            from cold_call_scripts import write_scripts_file
            scripts_path = out_dir / f'{filename_base}_Phone_Scripts.md'
            write_scripts_file(rows, str(scripts_path))
            result['phone_scripts'] = str(scripts_path)
        except ImportError:
            pass

    if os.environ.get('AIPL_GEN_EMAIL_TEMPLATES') == '1':
        try:
            from email_templates import write_emails_file
            emails_path = out_dir / f'{filename_base}_Email_Templates.md'
            write_emails_file(rows, str(emails_path))
            result['email_templates'] = str(emails_path)
        except ImportError:
            pass

    if os.environ.get('AIPL_GEN_LEAD_BRIEFS') == '1':
        try:
            from lead_brief import write_briefs_file
            briefs_path = out_dir / f'{filename_base}_Lead_Briefs.md'
            write_briefs_file(rows, str(briefs_path), top_n=20)
            result['lead_briefs'] = str(briefs_path)
        except ImportError:
            pass

    return result


def _extract_linkedin(r):
    """Pull a LinkedIn URL out of Additional Details for the team to click."""
    ad = str(r.get('Additional Details',''))
    m = re.search(r'(https?://(?:www\.)?linkedin\.com/[^\s|]+)', ad)
    return m.group(1) if m else ''


def _write_mode_b_action_sheet(rows, path):
    """
    Generate the Mode B Action Sheet — a printable per-tool todo list.
    Removes the 'which tool for which company' decision-making.
    Each tool gets its own section, prioritized, with LinkedIn URLs pre-filled
    and checkboxes the team ticks as they unlock each contact.

    Budget: 40 Lusha + 10 Apollo + 10 Signal Hire + 10 Contact Out = 65 credits/mo.
    """
    # Score every row and bucket by recommended tool
    buckets = {'Lusha': [], 'Apollo': [], 'Signal Hire': [], 'Contact Out': [],
               'Overflow': []}
    BUDGETS = {'Lusha': 40, 'Apollo': 10, 'Signal Hire': 10, 'Contact Out': 10}

    def assign(r, cat):
        """Pick the right tool for this row's gap type."""
        fn = str(r.get('First Name','')).strip()
        ln = str(r.get('Last Name','')).strip()
        em = str(r.get('Primary Email','')).strip()
        ph = str(r.get('Office Phone','')).strip() or str(r.get('Mobile Phone','')).strip()
        has_name = bool(fn or ln)
        if cat == 'CALL_GATEKEEPER':
            # Already have everything — DON'T queue for paid tools
            return None
        if cat == 'READY':
            return None
        if cat == 'CALL_SWITCHBOARD':
            # Blank, no info — Lusha for any phone they have
            return 'Lusha'
        if cat == 'MCA_LOOKUP':
            # No web presence — paid tools won't have them either
            return None
        if cat == 'LUSHA':
            return 'Lusha'
        if cat == 'APOLLO':
            # If have LinkedIn → Contact Out (LinkedIn→email specialty)
            if _extract_linkedin(r):
                return 'Contact Out'
            return 'Apollo'
        if cat == 'SKIP':
            return None
        # has name + missing both email AND phone → Signal Hire (bundle deal)
        if has_name and not em and not ph:
            return 'Signal Hire'
        return None

    # Sort by score so highest-value go in first
    SCORE = {'CALL_SWITCHBOARD': 10, 'LUSHA': 8, 'APOLLO': 7, 'MCA_LOOKUP': 0,
             'CALL_GATEKEEPER': 0, 'READY': 0, 'SKIP': 0, 'REVIEW': 0}
    scored = []
    for r in rows:
        cat, action = _classify_action(r)
        tool = assign(r, cat)
        if not tool:
            continue
        scored.append({
            'row':      r,
            'tool':     tool,
            'score':    SCORE.get(cat, 0),
            'reason':   action,
            'category': cat,
        })
    scored.sort(key=lambda x: -x['score'])

    # Fill tools to budget, overflow into 'Overflow'
    for item in scored:
        t = item['tool']
        if len(buckets.get(t, [])) < BUDGETS.get(t, 0):
            buckets[t].append(item)
        else:
            # Try fallback to another tool with capacity
            placed = False
            for alt in ['Lusha', 'Apollo', 'Signal Hire', 'Contact Out']:
                if alt != t and len(buckets[alt]) < BUDGETS[alt]:
                    item2 = dict(item); item2['tool'] = alt
                    item2['reason'] = f"(originally {t}; reassigned — {t} full)"
                    buckets[alt].append(item2)
                    placed = True
                    break
            if not placed:
                buckets['Overflow'].append(item)

    # ---- Write the Markdown ----
    with open(path, 'w', encoding='utf-8') as f:
        f.write('# AIPL Lead Enrichment — Mode B Action Sheet\n')
        f.write(f'_Generated: {date.today().strftime("%d %b %Y")}_\n\n')
        f.write('You have **65 free credits** across 4 paid B2B tools this month. ')
        f.write('Here is exactly which companies to look up where, in priority order. ')
        f.write('Tick the checkbox as you unlock each contact.\n\n')
        f.write('---\n\n')

        # Summary banner
        total_queued = sum(len(buckets[t]) for t in ('Lusha','Apollo','Signal Hire','Contact Out'))
        f.write(f'**Credit allocation:** ')
        for t in ('Lusha', 'Apollo', 'Signal Hire', 'Contact Out'):
            f.write(f'{t}: {len(buckets[t])}/{BUDGETS[t]}  ')
        f.write(f'  |  **Overflow** (next month): {len(buckets["Overflow"])}\n\n')
        f.write('---\n\n')

        # Per-tool sections
        TOOL_NOTES = {
            'Lusha':       'Best for **Indian mobile numbers**. Use the Chrome extension on LinkedIn profile pages.',
            'Apollo':      'Best for **IT-role emails at scale**. Search by job title at company.',
            'Signal Hire': 'Best for **senior decision-maker bundles** (name + email + phone in one unlock).',
            'Contact Out': 'Best for **email from a known LinkedIn profile**. Paste LI URL into extension.',
        }

        for tool in ('Lusha', 'Apollo', 'Signal Hire', 'Contact Out'):
            items = buckets[tool]
            f.write(f'## {tool} ({len(items)}/{BUDGETS[tool]} credits)\n\n')
            f.write(f'> {TOOL_NOTES[tool]}\n\n')
            if not items:
                f.write('_No companies queued for this tool this run._\n\n')
                continue
            for i, item in enumerate(items, 1):
                r  = item['row']
                fn = str(r.get('First Name','')).strip()
                ln = str(r.get('Last Name','')).strip()
                name = f'{fn} {ln}'.strip() or '_(no name yet)_'
                comp = str(r.get('Company',''))[:60]
                city = str(r.get('City',''))
                desg = str(r.get('Designation',''))
                li = _extract_linkedin(r)
                target = item['reason']
                f.write(f'- [ ] **{i}. {comp}** ({city})\n')
                f.write(f'      Current contact: {name} — {desg}\n')
                if li:
                    f.write(f'      LinkedIn: {li}\n')
                f.write(f'      What to get: {target}\n\n')

        # Overflow tab
        if buckets['Overflow']:
            f.write(f'## Overflow — next month ({len(buckets["Overflow"])} companies)\n\n')
            f.write('_Out of credits this month. Re-queue for next month_\n\n')
            for item in buckets['Overflow']:
                r = item['row']
                f.write(f'- [ ] {r.get("Company","")[:60]} — needed: {item["reason"]}\n')
            f.write('\n')

        # Closing instructions
        f.write('---\n\n')
        f.write('## When you are done with all 4 tools\n\n')
        f.write('1. Each tool lets you export your unlocked contacts as CSV. Download all 4.\n')
        f.write('2. Open a new Claude.ai chat. Upload the 4 CSVs + the master file from today.\n')
        f.write('3. Type: **"merge these tool exports into the master file"**\n')
        f.write('4. Claude auto-detects which tool each CSV is from + runs the merge.\n')
        f.write('5. Download the updated `Hygienic_Leads.csv` and import into Vtiger.\n\n')
        f.write('Total time: ~1 hour of clicking in browser extensions + 10 min of Claude chat.\n')


def _classify_action(r):
    """Decide what action the team should take for one Vtiger row."""
    fn = str(r.get('First Name','')).strip()
    ln = str(r.get('Last Name','')).strip()
    em = str(r.get('Primary Email','')).strip()
    ph = str(r.get('Office Phone','')).strip() or str(r.get('Mobile Phone','')).strip()
    desg = str(r.get('Designation','')).strip()
    comp_up = str(r.get('Company','')).strip().upper()
    ad = str(r.get('Additional Details','')).strip()

    has_name = bool(fn or ln)
    is_it = desg in ('VP IT / CISO / CTO','IT Manager / IT Head','IT Infra / Sr. IT Infra','IT Procurement / Purchase')
    is_gatekeeper = desg.startswith('Gatekeeper')

    if not has_name:
        if 'SAHAKARI' in comp_up or 'PATSANTHA' in comp_up:
            return ('SKIP', 'Cooperative society — not in any tool, accept blank')
        if 'NIDHI' in comp_up:
            return ('SKIP', 'Nidhi/NBFC — niche financial, low IT-sales fit')
        # If a prior research pass already confirmed "NOT_FOUND on aggregators — MCA lookup needed", route there
        if 'MCA portal' in ad or 'NOT_FOUND' in ad or 'recently incorporated' in ad.lower():
            return ('MCA_LOOKUP',
                    f'https://www.mca.gov.in/mcafoportal/viewCompanyMasterData.do '
                    f'→ "Find CIN/LLPIN" → enter "{str(r["Company"])[:60]}" → '
                    f'CAPTCHA → pull Director details. (Or set AIPL_OPENCORP_KEY '
                    f'env var to auto-fetch via OpenCorporates free API.)')
        _city_hint = str(r.get("City", "")).strip()  # use the row's city, don't assume Mumbai
        return ('CALL_SWITCHBOARD',
                f'JustDial search for "{str(r["Company"])[:35]}'
                + (f' {_city_hint}' if _city_hint else '') + ' switchboard"')

    if is_gatekeeper and not em and not ph:
        return ('NEEDS_RESEARCH',
                f'Have name only ({fn} {ln}) — use Phone_Scripts.md switchboard '
                f'script + JustDial search to find office phone, then call.')
    if is_gatekeeper and ph and not em:
        return ('CALL_GATEKEEPER',
                f'Call {fn} {ln} at {ph} — ask "may I speak to your IT Head?". '
                f'Use Phone_Scripts.md gatekeeper script.')
    if is_gatekeeper and em and ph:
        return ('CALL_GATEKEEPER',
                f'Call {fn} {ln} — ask "may I speak to the IT Head?". '
                f'Backup: send the email template from Email_Templates.md.')
    if is_it and em and ph:
        return ('READY', 'Fully enriched IT contact — call directly using Phone_Scripts.md script.')
    if is_it and not em:
        return ('COLD_EMAIL_NEEDED',
                'IT-role found, email is the gap. The skill\'s email_finder.py '
                'already tries MX-validated patterns. If still blank, use the '
                'Phone_Scripts.md script for direct phone outreach instead.')
    if is_it and not ph:
        return ('COLD_CALL_NEEDED',
                'IT-role found + email in hand, no phone yet. Send the '
                'Email_Templates.md email today + JustDial-search the switchboard '
                'for follow-up call in 3 days if no reply.')
    return ('REVIEW', 'Manual review needed')


def _write_actionable_coverage_report(rows, rpt_path):
    """Per-company next-action report — not just stats."""
    buckets = {}
    for r in rows:
        cat, action = _classify_action(r)
        buckets.setdefault(cat, []).append((r, action))

    n = len(rows)
    counts = {k: len(v) for k, v in buckets.items()}

    section_titles = {
        'READY':              '✓ READY TO CALL DIRECTLY (work these FIRST — use Phone_Scripts.md)',
        'CALL_GATEKEEPER':    '↻ CALL THE GATEKEEPER, ASK FOR IT HEAD (free — phone + script in hand)',
        'CALL_SWITCHBOARD':   '☎ COLD-CALL SWITCHBOARD (search JustDial for number — use Phone_Scripts.md switchboard script)',
        'MCA_LOOKUP':         '📋 MCA PORTAL LOOKUP (not on any aggregator — manual CAPTCHA lookup at mca.gov.in)',
        'COLD_EMAIL_NEEDED':  '📧 SEND COLD EMAIL (use Email_Templates.md — phone follow-up if no reply in 3 days)',
        'COLD_CALL_NEEDED':   '📞 COLD-CALL via JustDial + EMAIL (use Phone_Scripts.md + Email_Templates.md together)',
        'NEEDS_RESEARCH':     '🔍 FIND THEIR PHONE FIRST (JustDial → then call using switchboard script)',
        'SKIP':               '✗ SKIP — not worth chasing (cooperative / Nidhi / wrong segment)',
        'REVIEW':             '⚠ NEEDS MANUAL REVIEW',
    }

    with open(rpt_path, 'w', encoding='utf-8') as f:
        f.write('AIPL LEAD ENRICHMENT — ACTIONABLE COVERAGE REPORT\n')
        f.write(f'Generated: {date.today().strftime("%d %b %Y")}\n')
        f.write('='*70 + '\n\n')
        f.write(f'SUMMARY ({n} companies):\n')
        f.write(f'  ✓ Ready to call directly:              {counts.get("READY",0):3d}  (IT contact + email + phone — start here, use Phone_Scripts.md)\n')
        f.write(f'  ↻ Call gatekeeper, ask for IT Head:    {counts.get("CALL_GATEKEEPER",0):3d}  (have MD/Director with phone — gatekeeper script ready)\n')
        f.write(f'  ☎ Cold-call switchboard via JustDial:  {counts.get("CALL_SWITCHBOARD",0):3d}  (find phone on JustDial, use switchboard script)\n')
        f.write(f'  📋 MCA portal lookup needed:           {counts.get("MCA_LOOKUP",0):3d}  (very new Pvt Ltd — manual mca.gov.in lookup)\n')
        f.write(f'  📧 Cold email (template ready):        {counts.get("COLD_EMAIL_NEEDED",0):3d}  (use Email_Templates.md)\n')
        f.write(f'  📞 Cold call + email follow-up:        {counts.get("COLD_CALL_NEEDED",0):3d}  (Phone_Scripts.md + Email_Templates.md)\n')
        f.write(f'  🔍 Find phone first (no contact yet):  {counts.get("NEEDS_RESEARCH",0):3d}  (gatekeeper name only — JustDial then call)\n')
        f.write(f'  ✗ Skip (cooperative/Nidhi/wrong fit):  {counts.get("SKIP",0):3d}\n')
        f.write(f'  ⚠ Manual review needed:                {counts.get("REVIEW",0):3d}\n\n')

        for cat in ['READY','CALL_GATEKEEPER','CALL_SWITCHBOARD','MCA_LOOKUP',
                    'COLD_EMAIL_NEEDED','COLD_CALL_NEEDED','NEEDS_RESEARCH','SKIP','REVIEW']:
            rs = buckets.get(cat, [])
            if not rs: continue
            f.write('-'*70 + '\n')
            f.write(f'{section_titles[cat]} ({len(rs)} companies)\n')
            f.write('-'*70 + '\n')
            for r, action in rs:
                fn = str(r.get("First Name","")).strip()
                ln = str(r.get("Last Name","")).strip()
                name_str = f'{fn} {ln}'.strip() or '(no name)'
                ph = str(r.get("Office Phone","")).strip() or str(r.get("Mobile Phone","")).strip()
                ph_str = f' [{ph}]' if ph else ''
                em = str(r.get("Primary Email","")).strip()
                em_str = f' <{em}>' if em else ''
                f.write(f'  • {str(r["Company"])[:55]:<55} → {name_str[:25]:<25} ({str(r["Designation"])[:20]}){ph_str}{em_str}\n')
                if cat in ('CALL_SWITCHBOARD', 'MCA_LOOKUP'):
                    f.write(f'      ACTION: {action}\n')
            f.write('\n')
