"""
build_vtiger_file.py
====================
Takes a list of companies + per-company enrichment dicts and writes the final
Vtiger-ready files (XLSX + comma-CSV + coverage report).

This script runs in Claude.ai's analysis tool (Python sandbox). It uses only
pandas and openpyxl — both pre-installed. Web enrichment is done by Claude
BEFORE calling this script (via WebSearch / WebFetch); this script just formats.

USAGE (from within a Claude analysis tool block):
    from build_vtiger_file import build_files

    companies = [
        {"EnterpriseName": "ACME LIMITED", "Address": "...", "State": "...",
         "District": "MUMBAI", "Pincode": "400001"},
        ...
    ]
    enrichment = {
        "ACME LIMITED": {
            "first": "Anil", "last": "Kumar", "designation": "CIO",
            "email": "anil@acme.com", "phone": "022-12345678", "mobile": "",
            "website": "https://acme.com", "linkedin": "https://linkedin.com/in/anilkumar",
            "source_url": "https://www.zaubacorp.com/company/ACME-LIMITED",
            "confidence": "High", "cin": "L12345MH2000PLC123456",
            "notes": "Verified via company press release",
        },
        ...
    }
    paths = build_files(companies, enrichment, output_dir="/mnt/user-data/outputs")
    # Returns: {"xlsx": "...", "csv": "...", "report": "..."}
"""
import csv
import os
import re
from datetime import date
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font

# ----- 75-column Vtiger schema (exact order) -----
VTIGER_HEADERS = [
    'Lead ID','Company','Salutation','First Name','Last Name','Primary Email',
    'Designation','Location','Industry','Lead Generated on','Lead Generated By',
    'Lead Source','Lead Sub-Status','Lead Status','Office Phone','Created By',
    'Website','Mobile Phone','No. of Branches','Annual Revenue','Last Follow-up On',
    'Number of Employees','Created Time','Next follow-up on','Network Budget',
    'Modified Time','Requirement','Estimated Order Value','CreatedByExt',
    'Assigned To','ModifiedByExt','Record Currency','Last Modified By',
    'Record Conversion Rate','Source Campaign','Last Contacted Via',
    'Reason for Enquiry Lost','Request count','Lead Handled by',
    'Email Confirmation Last requested on','Email Opt-in','IT Users',
    'Primary Phone Field','Primary Email Field','Is closed?','Source',
    'Twitter Username','Engagement Score','Language','Timezone',
    'Facebook Lead ID','Ad Group','SMS opt-in','Fax','Platform','Country',
    'Street','PO Box','Postal Code','City','State','Latitude','Longitude',
    'Additional Details','Lead Image','Consent requested','Data erasure request',
    'Erased','Stop processing request','Track my email engagement',
    'Track my document engagement','Consent Last Requested Time','Facebook Id',
    'Instagram Id','Twitter Id',
]

CITY_FIXES = {
    'NAVI MUMBAI': 'Navi Mumbai', 'MUMBAI CITY': 'Mumbai',
    'KALYAN EAST': 'Kalyan', 'KALYAN': 'Kalyan',
    'BYCULLA': 'Byculla', 'TITWALA': 'Titwala',
    'PUNE': 'Pune', 'MUMBAI': 'Mumbai', 'THANE': 'Thane',
    'PAWANE': 'Navi Mumbai', 'WORLI': 'Mumbai',
    'VIKHROLI': 'Mumbai', 'BELAPUR': 'Navi Mumbai',
}

COMMON_FEMALE = {
    'priya','neha','pooja','reema','riya','asha','sneha','meera','radha',
    'sunita','geeta','seema','anita','kavita','smita','rekha','shilpa',
    'swati','ritu','divya','jyoti','rashmi','suman','nisha','manisha',
    'kiran','deepa','preeti','rachna','vandana','aarti','pallavi',
}

# Industry inference from company-name keywords
INDUSTRY_KEYWORDS = [
    ('Financial Services', ['financial','finance','capital','securities','bank','banking','investments','broking','asset','nidhi']),
    ('Oil & Gas',          ['oil','gas','petroleum','energy','natural gas']),
    ('Construction & Infra',['construction','builders','infra','realty','cement','steel','engineering','epc']),
    ('Logistics & Shipping',['logistics','shipping','transport','translogistics','transformers','cargo']),
    ('Pharmaceuticals',    ['pharma','pharmacle','laboratory','medical','healthcare','medicine','biosciences']),
    ('Manufacturing',      ['industries','manufactur','chemicals','emulsifiers','oils','fabric','plast']),
    ('IT & Software',      ['software','technology','tech ','systems','infotech','digital','innovations','edtech']),
    ('Travel & Hospitality',['travel','hospitality','tours','hotels']),
    ('Real Estate',        ['real estate','properties','estates','housing']),
    ('Agriculture',        ['agro','agri','shetkari','krishi','farming','agrovet']),
    ('Cooperative Society',['sahakari','patsantha','cooperative']),
]

def _city(d):
    if not d or pd.isna(d):
        return ''
    return CITY_FIXES.get(str(d).strip().upper(), str(d).strip().title())

def _normalize_phone(p):
    """Normalize Indian phone to +91-XX-XXXX-XXXX or +91-XXXXX-XXXXX (mobile)."""
    if not p: return ''
    p = str(p).strip()
    if not p or p.lower() == 'nan': return ''
    p = str(p).strip()
    digits = re.sub(r'[^\d]', '', p)

    # Toll-free (1800 / 1860): valid = 1800/1860 + 6-7 digits (10-11 total).
    # Format valid ones consistently; flag a wrong-length one so the team verifies
    # instead of dialing a broken number.
    if digits.startswith(('1800', '1860')):
        if len(digits) in (10, 11):
            return f'{digits[:4]}-{digits[4:7]}-{digits[7:]}'
        return f'{p}  (⚠ check length)'   # e.g. 1800-120-777778 (13 digits)

    # Reduce to the 10-digit national number (strip +91 / leading 0)
    core = digits
    if core.startswith('91') and len(core) == 12:
        core = core[2:]
    elif core.startswith('0') and len(core) == 11:
        core = core[1:]
    if len(core) != 10:
        return p  # not a standard 10-digit national number — leave as-is

    # Use the ORIGINAL formatting to disambiguate mobile vs landline:
    # the first digit-group is 5 for a mobile (98765-43210) but 2-3 for a
    # landline STD code (022-..., 80-...). This avoids mis-reading a Bangalore
    # (80) / Ahmedabad (79) landline as a mobile just because it starts 8/7.
    rest = re.sub(r'^\+?\s*91[\s\-.]?|^0', '', p)          # drop +91 / leading 0
    fg = re.match(r'[^\d]*(\d+)', rest)
    first_group_len = len(fg.group(1)) if fg else 0

    is_mobile = core[0] in '6789' and first_group_len not in (2, 3, 4)
    if is_mobile:
        return f'+91-{core[:5]}-{core[5:]}'
    # Landline: 2-digit metro STD vs 3-digit STD
    if core[:2] in {'11','20','22','33','40','44','79','80'}:
        return f'+91-{core[:2]}-{core[2:6]}-{core[6:]}'
    return f'+91-{core[:3]}-{core[3:6]}-{core[6:]}'

def _infer_industry(company):
    """Infer industry from explicit company-name keywords.
    Returns empty string if no keyword matches — NEVER guesses "Other / Diversified"
    (that was implying false certainty). Blank is honest.
    """
    cl = str(company or '').lower()
    for industry, kws in INDUSTRY_KEYWORDS:
        if any(k in cl for k in kws):
            return industry
    return ''  # honest — we don't know

def _clean_website(existing):
    """Sanitize the Website field. Returns the value only if it's a real URL.
    NEVER fabricates. If empty or invalid (e.g. email, phone), returns ''.
    """
    if not existing: return ''
    s = str(existing).strip()
    if not s or s.lower() == 'nan': return ''
    # Reject obvious non-URLs that leaked from bad source data
    if '@' in s:           return ''   # email in website column
    if re.match(r'^[\d\+\-\s()]+$', s): return ''  # phone number
    # Accept only if it looks like a URL or domain
    if s.startswith(('http://','https://','www.')) or re.match(r'^[\w-]+\.[\w-]+', s):
        return s
    return ''

def _salutation(first):
    f = (first or '').strip().lower()
    if not f: return ''
    if f in COMMON_FEMALE: return 'Ms.'
    # Heuristic: many Indian female names end in 'a' or 'i'
    if (f.endswith('a') or f.endswith('i')) and f not in {'krishna','vishnu','aditya','akash','manish','rajesh','suresh','ramesh','dinesh','prakash','ashish','satish','jatin'}:
        return 'Ms.'
    return 'Mr.'

# Acronyms kept UPPERCASE when tidying an all-lower / all-upper title
_TITLE_ACRONYMS = {'it','cio','cto','ciso','cdo','cdio','cto','ctdo','ctdto','vp','svp',
                   'evp','avp','hod','mis','edp','dgm','agm','gm','md','ceo','coo','cfo',
                   'cxo','ict','bfsi','hr','isms','soc'}

def _strip_title_notes(t):
    """Extract just the job TITLE from a verbose research string.
    Researchers sometimes append notes ('CEO - gatekeeper; no IT found',
    'CDO (role; last incumbent moved to TCS)'). A Designation should be a clean
    title, so cut those off (the context is already conveyed by the tier +
    gatekeeper prefix + notes elsewhere)."""
    t = str(t or '').strip()
    if not t:
        return ''
    # Cut at the first note separator (; or " - lowercase note" or ", no/gatekeeper…")
    t = re.split(r';|\s[-–]\s(?=[a-z])|,\s+(?=no\b|gatekeeper|former|role\b)', t)[0]
    # Protect short acronyms like (CTO), then strip longer parenthetical notes —
    # both closed "(role; …)" and UNCLOSED trailing "(role…" that runs to the end.
    t = re.sub(r'\(([A-Za-z/&]{1,8})\)', r'<<\1>>', t)   # protect short acronyms
    t = re.sub(r'\([^)]*\)', '', t)                       # remove closed notes
    t = re.sub(r'\([^)]*$', '', t)                        # remove unclosed trailing note
    t = t.replace('<<', '(').replace('>>', ')')
    # Drop trailing note phrases / role descriptors
    t = re.sub(r'(?i)\s*[-–]\s*(gatekeeper|no\s+(public\s+|dedicated\s+)?(it|cio|cto|ciso)|former|unverified|role\b).*$', '', t)
    t = re.sub(r'(?i)\bgatekeeper\b[;:].*$', '', t)
    # Drop a trailing ", <Company/group>" suffix the agents sometimes append
    t = re.sub(r',\s+[A-Z][\w&./ -]+$', '', t)
    t = re.sub(r'\s+', ' ', t).strip(' -–,;:/')
    # Word-boundary truncation (never cut mid-word like "Siem")
    if len(t) > 60:
        cut = t[:60].rsplit(' ', 1)[0]
        t = cut if cut else t[:60]
    return t.strip(' -–,;:/')


def _tidy_title(t):
    """Clean a verbatim job title — strip embedded notes, fix acronym casing."""
    t = _strip_title_notes(t)
    t = re.sub(r'\s+', ' ', t).strip(' -,–')
    if not t:
        return ''
    # Already mixed-case (e.g. "Chief Technology Officer") → trust it as-is
    if any(c.islower() for c in t) and any(c.isupper() for c in t):
        return t
    # All-upper or all-lower → title-case, but keep known acronyms uppercase
    out = []
    for w in t.split():
        core = re.sub(r'[^a-z]', '', w.lower())
        out.append(w.upper() if core in _TITLE_ACRONYMS else w.capitalize())
    return ' '.join(out)


def _map_designation(found, has_name=True):
    """
    Classify a job title. KEEPS THE REAL VERBATIM TITLE as the displayed
    designation (so the team sees "CTO" / "CISO" / "Head of IT" — not everyone
    flattened into one bucket), and ALSO returns the AIPL target-role TIER for
    filtering/prioritisation.

    Returns (display_designation, tier_bucket, is_it_role, is_default_placeholder)
      display_designation = the real title (IT roles) or "Gatekeeper - <title>"
      tier_bucket         = one of AIPL's 4 IT buckets, or '' for non-IT
    """
    if not found:
        if has_name:
            return ('Contact (role unconfirmed)', '', False, False)
        return ('', '', False, True)
    f = found.strip()
    fl = f.lower()
    disp = _tidy_title(f)

    # ---- Real IT decision-maker roles: SHOW the real title, tag the tier ----
    # Top tier: CIO/CTO/CISO/CDO/CDIO/CTDTO + VP/Head/Chief of IT/Tech/Digital/Security
    if re.search(r'\b(cio|cto|ciso|cdo|cdio|ct[dо]?to|cd?to|chief\s+(information|technolog|digital|security|data|innovation)\w*'
                 r'|chief\s+\w+\s+(information|technology|digital|security)\s+officer'
                 r'|vp\s*[-&]?\s*(it|ict|tech|technolog\w*|information|digital|infra\w*)'
                 r'|(vice[\s-]*president|head|director|gm|general\s+manager|sr\.?\s*vp|senior\s+vice[\s-]*president)\s*[-&,]?\s*'
                 r'(of\s+)?(it|ict|information\s+technolog\w*|technolog\w*|digital|cyber\s*security|information\s+security))\b', fl):
        return (disp, 'VP IT / CISO / CTO', True, False)
    if re.search(r'\b(it\s*infra\w*|infrastructure\s*(head|manager|lead|engineer)|network\s+(head|manager|admin)|datacent\w+\s+(head|manager))\b', fl):
        return (disp, 'IT Infra / Sr. IT Infra', True, False)
    if re.search(r'\b(it\s*(procurement|purchase|purchasing|sourcing)|(procurement|purchase)\s*head|head\s*[-,]?\s*(it\s*)?procurement)\b', fl):
        return (disp, 'IT Procurement / Purchase', True, False)
    if re.search(r'\b(it\s*(head|manager|lead|admin\w*)|head\s*[-,]?\s*it|head\s+of\s+(it|technolog\w*|digital|systems|mis)|manager\s*[-,]?\s*(it|systems|mis)|systems?\s+(head|manager|admin)|mis\s+(head|manager)|edp\s+(head|manager)|it\s+professional)\b', fl):
        return (disp, 'IT Manager / IT Head', True, False)

    # ---- Garbage placeholders ----
    if f in ('Care Of (Reg. Address)', 'Contact (role unspecified)', 'Head Office Contact'):
        return ('Contact (role unconfirmed)', '', False, False)

    # ---- Non-IT contacts: keep their REAL title under a Gatekeeper prefix ----
    return (f'Gatekeeper - {disp}', '', False, False)

# ---- v8.2 email helpers (person-first, no role inboxes, derive only from proof) ----
_ROLE_LOCALPARTS = {
    'grievance', 'grievances', 'info', 'care', 'customercare', 'customerservice',
    'customerfirst', 'customersupport', 'support', 'nodal', 'helpdesk', 'help',
    'contact', 'contactus', 'service', 'services', 'enquiry', 'enquiries',
    'investor', 'investors', 'cs', 'secretarial', 'secretary', 'compliance',
    'complaints', 'gro', 'headoffice', 'ho', 'feedback', 'claims', 'redressal',
    'redress', 'sales', 'marketing', 'admin', 'administration', 'hr', 'office',
    'mail', 'reachus', 'dpo', 'dpdp', 'helpline', 'customer', 'wecare', 'queries',
    'query', 'response', 'connect', 'hello', 'team', 'noreply', 'no-reply',
}


# Long, unambiguous role stems — safe to match even when concatenated with no
# separator (e.g. "indiaservice", "websupport"). Short/ambiguous ones (gro, care,
# info, hr, cs) are matched only as whole tokens to avoid hitting real names.
_ROLE_SUBSTRINGS = ('grievance', 'service', 'support', 'customer', 'nodal',
                    'complaint', 'redress', 'helpdesk', 'feedback', 'enquir',
                    'compliance', 'secretar', 'wecare', 'custcare')


def _is_role_inbox(email):
    """A generic/role mailbox (grievance@/info@/care@/fggro@) — never reaches the person."""
    if not email or '@' not in email:
        return False
    local = email.split('@', 1)[0].lower().strip()
    if local in _ROLE_LOCALPARTS:
        return True
    if any(t in _ROLE_LOCALPARTS for t in re.split(r'[._\-+]+', local)):
        return True
    if any(s in local for s in _ROLE_SUBSTRINGS):
        return True
    if local.endswith('gro'):           # GRO (grievance redressal officer) mailboxes
        return True
    return False


def _email_domain(s):
    """Domain from a website URL, a plain URL, or an email. '' if none usable."""
    if not s:
        return ''
    s = str(s).strip().lower()
    if not s or s == 'nan':
        return ''
    if '@' in s and ' ' not in s and '/' not in s:
        return s.split('@', 1)[1]
    s = s.split()[0]
    s = re.sub(r'^https?://', '', s).split('/')[0].split('?')[0]
    if s.startswith('www.'):
        s = s[4:]
    return s if re.match(r'^[\w-]+\.[\w.-]+$', s) else ''


def _base_domain(d):
    """Registrable base domain — strip subdomains so a pattern learned on
    'adityabirlacapital.com' still matches 'lifeinsurance.adityabirlacapital.com'."""
    parts = (d or '').split('.')
    if len(parts) <= 2:
        return d
    if parts[-2] in ('co', 'net', 'org', 'gov', 'ac', 'edu') and len(parts[-1]) == 2:
        return '.'.join(parts[-3:])          # e.g. co.in / co.uk
    return '.'.join(parts[-2:])


def _derive_email(first, last, domain, pattern):
    """Build the address for a cache-CONFIRMED company `pattern`. '' if the pattern
    needs a surname we don't have. This is the ONLY place the skill writes a derived
    address — and only when the pattern is proven by the team's own real data."""
    f = re.sub(r'[^a-z]', '', (first or '').lower())
    l = re.sub(r'[^a-z]', '', (last or '').lower())
    if not f or not domain:
        return ''
    fl, ll = f[:1], (l[:1] if l else '')
    if pattern != 'first' and not l:        # needs a surname we don't have
        return ''
    local = {
        'first.last': f'{f}.{l}', 'firstlast': f'{f}{l}', 'flast': f'{fl}{l}',
        'first': f, 'first_last': f'{f}_{l}', 'last.first': f'{l}.{f}',
        'first.l': f'{f}.{ll}', 'f.last': f'{fl}.{l}',
    }.get(pattern, '').strip('._-')
    return f'{local}@{domain}' if len(local) >= 2 else ''


def _build_row(src, enr, cache=None):
    """Build one Vtiger row from a source company dict + enrichment dict.
    `cache` (local_cache.Cache) enables v8.2 confirmed-pattern email derivation."""
    row = {h: '' for h in VTIGER_HEADERS}

    # ---- Defaults (apply to every row) ----
    row['Lead Generated on']      = date.today().strftime('%d/%m/%Y')
    row['Lead Source']            = 'Master DB'
    row['Lead Sub-Status']        = 'Not Connected'
    row['Lead Status']            = 'Prospect'
    row['Record Currency']        = 'INR'
    row['Record Conversion Rate'] = '1'
    row['Request count']          = '0'
    row['Email Opt-in']           = 'singleoptinuser'
    row['SMS opt-in']             = 'singleoptinuser'
    row['Is closed?']             = 'No'
    row['Source']                 = 'IMPORT'
    row['Engagement Score']       = '0'
    row['Country']                = 'India'

    # ---- Source address fields ----
    row['Company'] = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
    row['Street']  = str(src.get('Address') or '').strip()
    pin = src.get('Pincode') or src.get('Postal Code') or ''
    if pin and not pd.isna(pin):
        row['Postal Code'] = str(int(pin)) if isinstance(pin, (int, float)) else str(pin).strip()
    row['City']    = _city(src.get('District') or src.get('City'))
    # Don't assume Maharashtra — leave blank if the file didn't provide a state.
    # (AIPL's files cover multiple states; defaulting would mislabel them.)
    _state = str(src.get('State') or '').strip()
    row['State']   = _state.title() if _state and _state.lower() != 'nan' else ''

    # ---- Enrichment fields ----
    enr = enr or {}
    fn = (enr.get('first') or '').strip()
    ln = (enr.get('last') or '').strip()
    has_name = bool(fn or ln)
    found_title = (enr.get('designation') or '').strip()
    mapped_title, role_tier, is_it_role, is_default = _map_designation(found_title, has_name=has_name)

    # Salutation: only set if enrichment explicitly provided one (don't guess from name)
    row['Salutation']    = (enr.get('salutation') or '').strip()
    row['First Name']    = fn
    row['Last Name']     = ln
    # Designation now shows the REAL title (CTO/CIO/CISO/Head of IT/...), not a
    # one-size bucket. The AIPL target-role tier is stamped separately below.
    row['Designation']   = mapped_title
    # Internal tier (not a Vtiger column → not written to Excel) so the
    # scoring/action helpers can still recognise IT roles after we switched
    # Designation to the real verbatim title.
    row['_role_tier']    = role_tier
    # Primary Email is resolved by the v8.2 tiered waterfall below (after Website).
    # ---- Phone tiers (CEO's backup idea) ----
    # Office Phone = the best line we have: contact's office number, else the
    # company switchboard (so EVERY company with a findable number is callable).
    # Mobile Phone = contact's direct mobile if known.
    contact_phone   = _normalize_phone(enr.get('phone'))
    company_phone   = _normalize_phone(enr.get('company_phone'))
    it_dept_phone   = _normalize_phone(enr.get('it_phone'))
    # Backup chain (best → fallback): contact's own line → IT department line
    # → company switchboard. The IT-dept number is a BETTER backup than the
    # switchboard because it reaches IT directly instead of reception.
    row['Office Phone']  = contact_phone or it_dept_phone or company_phone
    row['Mobile Phone']  = _normalize_phone(enr.get('mobile'))
    row['Website']       = _clean_website(enr.get('website'))

    # ---- v8.2 Email resolution: tiered, person-first, NO role inboxes ----
    # Priority: researched person-email → confirmed-pattern derive (only where the
    # cache has a pattern PROVEN by the team's real data) → blank + intel.
    # A grievance@/info@ role inbox is NEVER the Primary Email — it doesn't reach
    # the person; it's parked in Additional Details as a fallback only.
    email_tier = role_inbox_note = email_intel = ''
    src_url = (enr.get('source_url') or '').strip()
    raw_email = (enr.get('email') or '').strip()
    if raw_email and '(pattern-guess' in raw_email.lower():
        raw_email = raw_email.split('(')[0].strip()          # drop any legacy guess tag
    # Prefer the REAL mail domain (from the email itself) over the website domain —
    # a company's site (bhartiaxa.com / a subdomain) often differs from its mail
    # domain (bharti-axalife.com), and the email's domain is the one patterns use.
    domain = ''
    if raw_email and _is_role_inbox(raw_email):
        role_inbox_note = raw_email                          # park it, not the person
        domain = raw_email.split('@', 1)[1].lower()          # the company's real mail domain
        raw_email = ''
    if raw_email and '@' in raw_email:
        row['Primary Email'] = raw_email                     # a real person-email
        # an explicit pre-set tier (e.g. a pattern-derived email injected upstream)
        # is honoured so derived addresses are never mislabelled "Confirmed".
        email_tier = (str(enr.get('email_confidence') or '').strip()
                      or ('Confirmed — published' if src_url else 'Confirmed — researched'))
        domain = domain or raw_email.split('@', 1)[1].lower()
    if not domain:
        domain = _email_domain(row['Website']) or _email_domain(src_url)
    # No person-email yet → derive ONLY from a cache pattern proven by real data
    if not row['Primary Email'] and has_name and domain and cache is not None:
        try:
            pat, conf = cache.lookup_pattern(domain)
            if not pat:                                      # try the registrable base domain
                base = _base_domain(domain)
                if base and base != domain:
                    pat, conf = cache.lookup_pattern(base)
                    if pat:
                        domain = base
        except Exception:
            pat, conf = (None, None)
        if pat and conf in ('High', 'Medium'):
            derived = _derive_email(fn, ln, domain, pat)
            if derived:
                row['Primary Email'] = derived
                email_tier = f'Verified-pattern ({pat}, {conf} — from your DB)'
        if not row['Primary Email']:
            hint = (f' — likely {pat}@{domain}' if pat else (f' on {domain}' if domain else ''))
            email_intel = (f"NO confirmed email — contact is {(fn + ' ' + ln).strip()}{hint}; "
                           f"confirm on the company site/exhibitor listing, or spend 1 free "
                           f"Apollo/Lusha credit on this name").strip()

    # ---- Marketing-team defaults (so Vtiger doesn't require manual assign) ----
    row['Industry']        = _infer_industry(row['Company'])
    row['Lead Handled by'] = 'Marketing Team'
    row['Assigned To']     = 'Marketing Team'

    # ---- Additional Details: stash provenance ----
    details = []
    # AIPL target-role tier (for the team to filter on, since Designation now
    # shows the real varied title instead of the bucket).
    if role_tier:
        details.append(f'IT ROLE TIER: {role_tier}')
    # v8.2 Email confidence — so the team knows exactly how solid the address is.
    if email_tier:
        details.append(f'EMAIL CONFIDENCE: {email_tier}')
    if role_inbox_note:
        details.append(f'ORG FALLBACK INBOX (not the person): {role_inbox_note}')
    if email_intel:
        details.append(f'EMAIL: {email_intel}')
    # CEO's backup idea — label which tier the Office Phone is + list the backups.
    if contact_phone:
        details.append("PHONE TIER: contact's own line (Office Phone)")
    elif it_dept_phone and row['Office Phone'] == it_dept_phone:
        details.append('PHONE TIER: IT-department line in Office Phone (backup 1 — reaches IT directly)')
    elif company_phone and row['Office Phone'] == company_phone:
        details.append('PHONE TIER: company switchboard in Office Phone (backup 2 — ask reception for IT Head)')
    # Always list the other backups so the team has fallbacks
    if it_dept_phone and it_dept_phone != row['Office Phone']:
        details.append(f'IT DEPT PHONE (backup): {it_dept_phone} — direct line into IT')
    if company_phone and company_phone != row['Office Phone']:
        details.append(f'COMPANY SWITCHBOARD (backup): {company_phone}')

    # ---- No phone found anywhere → tell the team EXACTLY where to grab it (30 sec) ----
    # The number usually exists but is gated behind JustDial's "Show Number" (which
    # we won't scrape) or not freely published. Instead of a dead blank, hand the
    # team a ready manual lookup so they can reveal it themselves.
    if not row['Office Phone'] and not row['Mobile Phone']:
        comp_q  = str(row['Company']).strip()
        city_q  = str(row.get('City','')).strip()
        gq = (comp_q + (' ' + city_q if city_q else '')).replace(' ', '+')
        details.append(
            f"📞 NO FREE PHONE FOUND — get it manually (~30 sec): "
            f"JustDial → search \"{comp_q}{(' ' + city_q) if city_q else ''}\" → click "
            f"'Show Number'. Or Google: https://www.google.com/search?q={gq}+phone+contact"
        )
    # Only flag if the title looked IT-like at first glance but didn't match an IT bucket
    # (mapped_title starts with "Gatekeeper -" already communicates the rest)
    if (fn or ln) and not is_it_role and found_title and not mapped_title.startswith('Gatekeeper'):
        details.append('ROLE FLAG: Not IT-specific — use as gatekeeper to reach IT decision-maker')
    cin = (enr.get('cin') or '').strip()
    linkedin = (enr.get('linkedin') or '').strip()
    source_url = (enr.get('source_url') or '').strip()
    confidence = (enr.get('confidence') or '').strip()
    notes = (enr.get('notes') or '').strip()
    if cin:        details.append(f'CIN: {cin}')
    if linkedin:   details.append(f'LinkedIn: {linkedin}')
    if source_url: details.append(f'Source: {source_url}')
    if confidence: details.append(f'Confidence: {confidence}')
    if notes:      details.append(f'Notes: {notes}')
    row['Additional Details'] = ' | '.join(details)
    return row

def _merge_cache_into_enrichment(companies, enrichment):
    """
    For each company, check the local SQLite cache. If we have a higher-confidence
    contact cached (from prior runs or team-verified), use it. Otherwise, when
    fresh enrichment is provided, save it back to the cache.

    This is the FLYWHEEL: every run improves future runs.
    """
    try:
        from local_cache import Cache
        cache = Cache()
    except Exception:
        return enrichment  # cache optional; never fail the build

    CONF_RANK = {'High': 0, 'Medium': 1, 'Low': 2, '': 3, None: 3}
    merged = dict(enrichment or {})

    # v7.2: re-verify cached emails via MX so we don't serve dead/wrong addresses
    try:
        from email_finder import _has_mx, _domain_from_website
        _can_verify = True
    except Exception:
        _can_verify = False

    def _email_still_valid(email):
        """Cheap MX re-check on a cached email. True if domain still accepts mail."""
        if not email or '@' not in email:
            return False
        if not _can_verify:
            return True  # can't check — assume ok rather than drop
        domain = email.split('@', 1)[1].strip().lower()
        try:
            return _has_mx(domain)
        except Exception:
            return True  # network hiccup — don't punish the cached data

    for src in companies:
        name = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
        if not name:
            continue
        hit = cache.lookup_company(name)
        fresh = merged.get(name, {}) or {}

        if hit and hit.get('best'):
            cached = hit['best']
            fresh_conf  = CONF_RANK.get((fresh.get('confidence') or '').title(), 3)
            cached_conf = CONF_RANK.get((cached.get('confidence') or '').title(), 3)
            is_stale    = cached.get('is_stale', False)
            days_old    = cached.get('days_old', 0)

            # ---- v7.2 RULE: FRESH RESEARCH ALWAYS WINS ----
            # Only fall back to cache for fields the fresh pass DIDN'T find.
            # Cache never overrides a value fresh research produced this run.
            cached_email = cached.get('email', '')
            # Re-verify cached email before serving it
            if cached_email and not _email_still_valid(cached_email):
                cached_email = ''  # drop dead email — don't serve it

            # Downgrade confidence on stale cache so the team knows to re-check
            if is_stale:
                cache_conf_label = 'Low'   # stale → never High
                stale_note = f"⚠ CACHED {days_old}d ago (STALE — re-verify before calling)"
            else:
                cache_conf_label = 'Medium' if cached.get('confidence') == 'High' else cached.get('confidence', 'Low')
                stale_note = f"Cached {days_old}d ago — verify before calling"

            merged[name] = {
                # Fresh value if present, else fall back to cache (fill-gaps only)
                'first':       fresh.get('first')       or cached.get('first_name', ''),
                'last':        fresh.get('last')        or cached.get('last_name', ''),
                'designation': fresh.get('designation') or cached.get('designation', ''),
                'email':       fresh.get('email')       or cached_email,
                # preserve a fresh pre-set email tier (e.g. pattern-derived) so the
                # cache-merge never relabels a derived address as "Confirmed".
                'email_confidence': fresh.get('email_confidence', ''),
                'phone':       fresh.get('phone')       or cached.get('phone', ''),
                'mobile':      fresh.get('mobile')      or cached.get('mobile', ''),
                # v7.7.2 FIX: preserve the company-switchboard + IT-dept backups
                # through the cache. Without these two lines, every cache hit
                # silently dropped the switchboard numbers (halving phone coverage
                # on repeat runs).
                'company_phone': fresh.get('company_phone') or cached.get('company_phone', ''),
                'it_phone':      fresh.get('it_phone')      or cached.get('it_phone', ''),
                'website':     fresh.get('website')     or hit['company'].get('website', ''),
                'linkedin':    fresh.get('linkedin')    or cached.get('linkedin', ''),
                'source_url':  fresh.get('source_url')  or cached.get('source_url', ''),
                # Confidence = fresh's if fresh found a name; else downgraded cache label
                'confidence':  (fresh.get('confidence') if fresh.get('first') or fresh.get('last')
                                else cache_conf_label),
                'cin':         fresh.get('cin')         or hit['company'].get('cin', ''),
                'notes':       ((fresh.get('notes','') + ' | ' if fresh.get('notes') else '') +
                                (stale_note if not (fresh.get('first') or fresh.get('last')) else '')
                               ).strip(' |'),
            }

        # Save fresh enrichment back to cache for future runs (if we have a name)
        if fresh and (fresh.get('first') or fresh.get('last') or fresh.get('email')):
            cache.save_company(name,
                website=fresh.get('website',''),
                city=str(src.get('District') or src.get('City') or ''),
                state=str(src.get('State','')),
                address=str(src.get('Address','')),
                pincode=str(src.get('Pincode','')),
            )
            # Cache hygiene: a pattern-DERIVED email is high-probability, not
            # verified — don't store it as a confirmed cached contact (it would
            # later resurface as "Confirmed" and lose its derived tier). Save the
            # name/phone, but blank the derived email so it's always re-derived.
            to_save = fresh
            if str(fresh.get('email_confidence', '')).startswith('Verified-pattern'):
                to_save = dict(fresh); to_save['email'] = ''
            cache.save_contact(name, to_save)

    cache.close()
    return merged


def build_files(companies, enrichment, output_dir='/mnt/user-data/outputs', filename_base='Hygienic_Leads'):
    """
    Build all three output files.

    companies: list of dicts with at least EnterpriseName/Company + address fields
    enrichment: dict keyed by company name -> enrichment dict
                {first, last, designation, email, phone, mobile, website,
                 linkedin, source_url, confidence, cin, notes}
    output_dir: where to write the files (Claude analysis tool default works)
    filename_base: base filename (default "Hygienic_Leads")

    Returns dict of paths: {"xlsx", "csv", "report"}
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    xlsx_path = out_dir / f'{filename_base}.xlsx'
    csv_path  = out_dir / f'{filename_base}.csv'
    rpt_path  = out_dir / f'{filename_base}_Coverage_Report.txt'

    # ---- Cache flywheel: merge with prior verified contacts + save fresh ones ----
    enrichment = _merge_cache_into_enrichment(companies, enrichment)

    # v8.2: open the cache once so _build_row can derive emails from CONFIRMED
    # per-domain patterns (learned from the team's own hygienic DB). Degrades
    # gracefully to no-derivation if the cache can't be opened.
    try:
        from local_cache import Cache
        _cache = Cache()
    except Exception:
        _cache = None

    rows = []
    for src in companies:
        key = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
        enr = enrichment.get(key, {})
        rows.append(_build_row(src, enr, cache=_cache))

    # ---- XLSX (for human review) ----
    wb = Workbook()
    ws = wb.active
    ws.title = 'Vtiger_Leads'
    ws.append(VTIGER_HEADERS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    for r in rows:
        ws.append([r[h] for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws.cell(row=1, column=ci).column_letter
        ws.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws.freeze_panes = 'A2'
    wb.save(xlsx_path)

    # ---- Comma-CSV (for Vtiger import) ----
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL, extrasaction='ignore')
        w.writeheader()
        w.writerows(rows)

    # ---- v6: Sales priority tagging (Hot/Warm/Cold) ----
    try:
        from sales_priority import score as _priority_score
        for r in rows:
            tier, reason = _priority_score(r)
            r['Source Campaign'] = tier  # stamp priority in Vtiger col
            # Append reason to Additional Details
            existing_ad = r.get('Additional Details', '')
            r['Additional Details'] = (
                (existing_ad + ' | ' if existing_ad else '') +
                f"Priority: {tier} ({reason})"
            ).strip(' |')
    except ImportError:
        pass  # v5 fallback — skill works without sales_priority

    # ---- v7: Pack action recommendation INTO the XLSX itself ----
    # Use the "Reason for Enquiry Lost" unused Vtiger field to store the
    # team's next-action per company. This way the XLSX is the single
    # source of truth — team can filter/sort by this column.
    for r in rows:
        cat, action = _classify_action(r)
        r['Reason for Enquiry Lost'] = cat  # filterable bucket name
        # Stash the human-readable action in Additional Details
        existing_ad = r.get('Additional Details', '')
        r['Additional Details'] = (
            (existing_ad + ' | ' if existing_ad else '') +
            f"Next Action: {action}"
        ).strip(' |')

    # Re-write XLSX + CSV with the priority stamps
    # (the xlsx/csv above were written WITHOUT Source Campaign — overwrite now)
    wb2 = Workbook()
    ws2 = wb2.active
    ws2.title = 'Vtiger_Leads'
    ws2.append(VTIGER_HEADERS)
    for cell in ws2[1]:
        cell.font = Font(bold=True)
    for r in rows:
        ws2.append([r.get(h, '') for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws2.cell(row=1, column=ci).column_letter
        ws2.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws2.freeze_panes = 'A2'
    wb2.save(xlsx_path)
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL, extrasaction='ignore')
        w.writeheader()
        w.writerows(rows)

    # ============================================================
    # v7: DEFAULT OUTPUT = XLSX + CSV ONLY
    # Everything else is opt-in via env vars (or kwargs). Keeps the
    # output lean — all the value packed into the two import-ready files.
    #
    # To enable extras, set ANY of:
    #   AIPL_GEN_COVERAGE_REPORT=1   → generate Coverage_Report.txt
    #   AIPL_GEN_PHONE_SCRIPTS=1     → generate Phone_Scripts.md
    #   AIPL_GEN_EMAIL_TEMPLATES=1   → generate Email_Templates.md
    #   AIPL_GEN_LEAD_BRIEFS=1       → generate Lead_Briefs.md
    #   AIPL_ENABLE_PAID_TOOLS=1     → generate Paid_Tool_Sheet.md
    # ============================================================
    result = {
        'xlsx': str(xlsx_path),
        'csv':  str(csv_path),
    }

    if os.environ.get('AIPL_GEN_COVERAGE_REPORT') == '1':
        _write_actionable_coverage_report(rows, rpt_path)
        result['report'] = str(rpt_path)

    if os.environ.get('AIPL_ENABLE_PAID_TOOLS') == '1':
        action_path = out_dir / f'{filename_base}_Paid_Tool_Sheet.md'
        _write_mode_b_action_sheet(rows, action_path)
        result['paid_tool_sheet'] = str(action_path)

    if os.environ.get('AIPL_GEN_PHONE_SCRIPTS') == '1':
        try:
            from cold_call_scripts import write_scripts_file
            scripts_path = out_dir / f'{filename_base}_Phone_Scripts.md'
            write_scripts_file(rows, str(scripts_path))
            result['phone_scripts'] = str(scripts_path)
        except ImportError:
            pass

    if os.environ.get('AIPL_GEN_EMAIL_TEMPLATES') == '1':
        try:
            from email_templates import write_emails_file
            emails_path = out_dir / f'{filename_base}_Email_Templates.md'
            write_emails_file(rows, str(emails_path))
            result['email_templates'] = str(emails_path)
        except ImportError:
            pass

    if os.environ.get('AIPL_GEN_LEAD_BRIEFS') == '1':
        try:
            from lead_brief import write_briefs_file
            briefs_path = out_dir / f'{filename_base}_Lead_Briefs.md'
            write_briefs_file(rows, str(briefs_path), top_n=20)
            result['lead_briefs'] = str(briefs_path)
        except ImportError:
            pass

    return result


def _extract_linkedin(r):
    """Pull a LinkedIn URL out of Additional Details for the team to click."""
    ad = str(r.get('Additional Details',''))
    m = re.search(r'(https?://(?:www\.)?linkedin\.com/[^\s|]+)', ad)
    return m.group(1) if m else ''


def _write_mode_b_action_sheet(rows, path):
    """
    Generate the Mode B Action Sheet — a printable per-tool todo list.
    Removes the 'which tool for which company' decision-making.
    Each tool gets its own section, prioritized, with LinkedIn URLs pre-filled
    and checkboxes the team ticks as they unlock each contact.

    Budget: 40 Lusha + 10 Apollo + 10 Signal Hire + 10 Contact Out = 65 credits/mo.
    """
    # Score every row and bucket by recommended tool
    buckets = {'Lusha': [], 'Apollo': [], 'Signal Hire': [], 'Contact Out': [],
               'Overflow': []}
    BUDGETS = {'Lusha': 40, 'Apollo': 10, 'Signal Hire': 10, 'Contact Out': 10}

    def assign(r, cat):
        """Pick the right tool for this row's gap type."""
        fn = str(r.get('First Name','')).strip()
        ln = str(r.get('Last Name','')).strip()
        em = str(r.get('Primary Email','')).strip()
        ph = str(r.get('Office Phone','')).strip() or str(r.get('Mobile Phone','')).strip()
        has_name = bool(fn or ln)
        if cat == 'CALL_GATEKEEPER':
            # Already have everything — DON'T queue for paid tools
            return None
        if cat == 'READY':
            return None
        if cat == 'CALL_SWITCHBOARD':
            # Blank, no info — Lusha for any phone they have
            return 'Lusha'
        if cat == 'MCA_LOOKUP':
            # No web presence — paid tools won't have them either
            return None
        if cat == 'LUSHA':
            return 'Lusha'
        if cat == 'APOLLO':
            # If have LinkedIn → Contact Out (LinkedIn→email specialty)
            if _extract_linkedin(r):
                return 'Contact Out'
            return 'Apollo'
        if cat == 'SKIP':
            return None
        # has name + missing both email AND phone → Signal Hire (bundle deal)
        if has_name and not em and not ph:
            return 'Signal Hire'
        return None

    # Sort by score so highest-value go in first
    SCORE = {'CALL_SWITCHBOARD': 10, 'LUSHA': 8, 'APOLLO': 7, 'MCA_LOOKUP': 0,
             'CALL_GATEKEEPER': 0, 'READY': 0, 'SKIP': 0, 'REVIEW': 0}
    scored = []
    for r in rows:
        cat, action = _classify_action(r)
        tool = assign(r, cat)
        if not tool:
            continue
        scored.append({
            'row':      r,
            'tool':     tool,
            'score':    SCORE.get(cat, 0),
            'reason':   action,
            'category': cat,
        })
    scored.sort(key=lambda x: -x['score'])

    # Fill tools to budget, overflow into 'Overflow'
    for item in scored:
        t = item['tool']
        if len(buckets.get(t, [])) < BUDGETS.get(t, 0):
            buckets[t].append(item)
        else:
            # Try fallback to another tool with capacity
            placed = False
            for alt in ['Lusha', 'Apollo', 'Signal Hire', 'Contact Out']:
                if alt != t and len(buckets[alt]) < BUDGETS[alt]:
                    item2 = dict(item); item2['tool'] = alt
                    item2['reason'] = f"(originally {t}; reassigned — {t} full)"
                    buckets[alt].append(item2)
                    placed = True
                    break
            if not placed:
                buckets['Overflow'].append(item)

    # ---- Write the Markdown ----
    with open(path, 'w', encoding='utf-8') as f:
        f.write('# AIPL Lead Enrichment — Mode B Action Sheet\n')
        f.write(f'_Generated: {date.today().strftime("%d %b %Y")}_\n\n')
        f.write('You have **65 free credits** across 4 paid B2B tools this month. ')
        f.write('Here is exactly which companies to look up where, in priority order. ')
        f.write('Tick the checkbox as you unlock each contact.\n\n')
        f.write('---\n\n')

        # Summary banner
        total_queued = sum(len(buckets[t]) for t in ('Lusha','Apollo','Signal Hire','Contact Out'))
        f.write(f'**Credit allocation:** ')
        for t in ('Lusha', 'Apollo', 'Signal Hire', 'Contact Out'):
            f.write(f'{t}: {len(buckets[t])}/{BUDGETS[t]}  ')
        f.write(f'  |  **Overflow** (next month): {len(buckets["Overflow"])}\n\n')
        f.write('---\n\n')

        # Per-tool sections
        TOOL_NOTES = {
            'Lusha':       'Best for **Indian mobile numbers**. Use the Chrome extension on LinkedIn profile pages.',
            'Apollo':      'Best for **IT-role emails at scale**. Search by job title at company.',
            'Signal Hire': 'Best for **senior decision-maker bundles** (name + email + phone in one unlock).',
            'Contact Out': 'Best for **email from a known LinkedIn profile**. Paste LI URL into extension.',
        }

        for tool in ('Lusha', 'Apollo', 'Signal Hire', 'Contact Out'):
            items = buckets[tool]
            f.write(f'## {tool} ({len(items)}/{BUDGETS[tool]} credits)\n\n')
            f.write(f'> {TOOL_NOTES[tool]}\n\n')
            if not items:
                f.write('_No companies queued for this tool this run._\n\n')
                continue
            for i, item in enumerate(items, 1):
                r  = item['row']
                fn = str(r.get('First Name','')).strip()
                ln = str(r.get('Last Name','')).strip()
                name = f'{fn} {ln}'.strip() or '_(no name yet)_'
                comp = str(r.get('Company',''))[:60]
                city = str(r.get('City',''))
                desg = str(r.get('Designation',''))
                li = _extract_linkedin(r)
                target = item['reason']
                f.write(f'- [ ] **{i}. {comp}** ({city})\n')
                f.write(f'      Current contact: {name} — {desg}\n')
                if li:
                    f.write(f'      LinkedIn: {li}\n')
                f.write(f'      What to get: {target}\n\n')

        # Overflow tab
        if buckets['Overflow']:
            f.write(f'## Overflow — next month ({len(buckets["Overflow"])} companies)\n\n')
            f.write('_Out of credits this month. Re-queue for next month_\n\n')
            for item in buckets['Overflow']:
                r = item['row']
                f.write(f'- [ ] {r.get("Company","")[:60]} — needed: {item["reason"]}\n')
            f.write('\n')

        # Closing instructions
        f.write('---\n\n')
        f.write('## When you are done with all 4 tools\n\n')
        f.write('1. Each tool lets you export your unlocked contacts as CSV. Download all 4.\n')
        f.write('2. Open a new Claude.ai chat. Upload the 4 CSVs + the master file from today.\n')
        f.write('3. Type: **"merge these tool exports into the master file"**\n')
        f.write('4. Claude auto-detects which tool each CSV is from + runs the merge.\n')
        f.write('5. Download the updated `Hygienic_Leads.csv` and import into Vtiger.\n\n')
        f.write('Total time: ~1 hour of clicking in browser extensions + 10 min of Claude chat.\n')


def _classify_action(r):
    """Decide what action the team should take for one Vtiger row."""
    fn = str(r.get('First Name','')).strip()
    ln = str(r.get('Last Name','')).strip()
    em = str(r.get('Primary Email','')).strip()
    ph = str(r.get('Office Phone','')).strip() or str(r.get('Mobile Phone','')).strip()
    desg = str(r.get('Designation','')).strip()
    comp_up = str(r.get('Company','')).strip().upper()
    ad = str(r.get('Additional Details','')).strip()

    has_name = bool(fn or ln)
    # Designation now holds the REAL title, so detect IT roles via the internal
    # tier (falls back to the role-tier note in Additional Details).
    tier = str(r.get('_role_tier','')).strip()
    is_it = bool(tier) or 'IT ROLE TIER:' in ad
    is_gatekeeper = desg.startswith('Gatekeeper')

    if not has_name:
        if 'SAHAKARI' in comp_up or 'PATSANTHA' in comp_up:
            return ('SKIP', 'Cooperative society — not in any tool, accept blank')
        if 'NIDHI' in comp_up:
            return ('SKIP', 'Nidhi/NBFC — niche financial, low IT-sales fit')
        # If a prior research pass already confirmed "NOT_FOUND on aggregators — MCA lookup needed", route there
        if 'MCA portal' in ad or 'NOT_FOUND' in ad or 'recently incorporated' in ad.lower():
            return ('MCA_LOOKUP',
                    f'https://www.mca.gov.in/mcafoportal/viewCompanyMasterData.do '
                    f'→ "Find CIN/LLPIN" → enter "{str(r["Company"])[:60]}" → '
                    f'CAPTCHA → pull Director details. (Or set AIPL_OPENCORP_KEY '
                    f'env var to auto-fetch via OpenCorporates free API.)')
        _city_hint = str(r.get("City", "")).strip()  # use the row's city, don't assume Mumbai
        return ('CALL_SWITCHBOARD',
                f'JustDial search for "{str(r["Company"])[:35]}'
                + (f' {_city_hint}' if _city_hint else '') + ' switchboard"')

    if is_gatekeeper and not em and not ph:
        return ('NEEDS_RESEARCH',
                f'Have name only ({fn} {ln}) — use Phone_Scripts.md switchboard '
                f'script + JustDial search to find office phone, then call.')
    if is_gatekeeper and ph and not em:
        return ('CALL_GATEKEEPER',
                f'Call {fn} {ln} at {ph} — ask "may I speak to your IT Head?". '
                f'Use Phone_Scripts.md gatekeeper script.')
    if is_gatekeeper and em and ph:
        return ('CALL_GATEKEEPER',
                f'Call {fn} {ln} — ask "may I speak to the IT Head?". '
                f'Backup: send the email template from Email_Templates.md.')
    if is_it and em and ph:
        return ('READY', 'Fully enriched IT contact — call directly using Phone_Scripts.md script.')
    if is_it and not em:
        return ('COLD_EMAIL_NEEDED',
                'IT-role found, email is the gap. The skill\'s email_finder.py '
                'already tries MX-validated patterns. If still blank, use the '
                'Phone_Scripts.md script for direct phone outreach instead.')
    if is_it and not ph:
        return ('COLD_CALL_NEEDED',
                'IT-role found + email in hand, no phone yet. Send the '
                'Email_Templates.md email today + JustDial-search the switchboard '
                'for follow-up call in 3 days if no reply.')
    return ('REVIEW', 'Manual review needed')


def _write_actionable_coverage_report(rows, rpt_path):
    """Per-company next-action report — not just stats."""
    buckets = {}
    for r in rows:
        cat, action = _classify_action(r)
        buckets.setdefault(cat, []).append((r, action))

    n = len(rows)
    counts = {k: len(v) for k, v in buckets.items()}

    section_titles = {
        'READY':              '✓ READY TO CALL DIRECTLY (work these FIRST — use Phone_Scripts.md)',
        'CALL_GATEKEEPER':    '↻ CALL THE GATEKEEPER, ASK FOR IT HEAD (free — phone + script in hand)',
        'CALL_SWITCHBOARD':   '☎ COLD-CALL SWITCHBOARD (search JustDial for number — use Phone_Scripts.md switchboard script)',
        'MCA_LOOKUP':         '📋 MCA PORTAL LOOKUP (not on any aggregator — manual CAPTCHA lookup at mca.gov.in)',
        'COLD_EMAIL_NEEDED':  '📧 SEND COLD EMAIL (use Email_Templates.md — phone follow-up if no reply in 3 days)',
        'COLD_CALL_NEEDED':   '📞 COLD-CALL via JustDial + EMAIL (use Phone_Scripts.md + Email_Templates.md together)',
        'NEEDS_RESEARCH':     '🔍 FIND THEIR PHONE FIRST (JustDial → then call using switchboard script)',
        'SKIP':               '✗ SKIP — not worth chasing (cooperative / Nidhi / wrong segment)',
        'REVIEW':             '⚠ NEEDS MANUAL REVIEW',
    }

    with open(rpt_path, 'w', encoding='utf-8') as f:
        f.write('AIPL LEAD ENRICHMENT — ACTIONABLE COVERAGE REPORT\n')
        f.write(f'Generated: {date.today().strftime("%d %b %Y")}\n')
        f.write('='*70 + '\n\n')
        f.write(f'SUMMARY ({n} companies):\n')
        f.write(f'  ✓ Ready to call directly:              {counts.get("READY",0):3d}  (IT contact + email + phone — start here, use Phone_Scripts.md)\n')
        f.write(f'  ↻ Call gatekeeper, ask for IT Head:    {counts.get("CALL_GATEKEEPER",0):3d}  (have MD/Director with phone — gatekeeper script ready)\n')
        f.write(f'  ☎ Cold-call switchboard via JustDial:  {counts.get("CALL_SWITCHBOARD",0):3d}  (find phone on JustDial, use switchboard script)\n')
        f.write(f'  📋 MCA portal lookup needed:           {counts.get("MCA_LOOKUP",0):3d}  (very new Pvt Ltd — manual mca.gov.in lookup)\n')
        f.write(f'  📧 Cold email (template ready):        {counts.get("COLD_EMAIL_NEEDED",0):3d}  (use Email_Templates.md)\n')
        f.write(f'  📞 Cold call + email follow-up:        {counts.get("COLD_CALL_NEEDED",0):3d}  (Phone_Scripts.md + Email_Templates.md)\n')
        f.write(f'  🔍 Find phone first (no contact yet):  {counts.get("NEEDS_RESEARCH",0):3d}  (gatekeeper name only — JustDial then call)\n')
        f.write(f'  ✗ Skip (cooperative/Nidhi/wrong fit):  {counts.get("SKIP",0):3d}\n')
        f.write(f'  ⚠ Manual review needed:                {counts.get("REVIEW",0):3d}\n\n')

        for cat in ['READY','CALL_GATEKEEPER','CALL_SWITCHBOARD','MCA_LOOKUP',
                    'COLD_EMAIL_NEEDED','COLD_CALL_NEEDED','NEEDS_RESEARCH','SKIP','REVIEW']:
            rs = buckets.get(cat, [])
            if not rs: continue
            f.write('-'*70 + '\n')
            f.write(f'{section_titles[cat]} ({len(rs)} companies)\n')
            f.write('-'*70 + '\n')
            for r, action in rs:
                fn = str(r.get("First Name","")).strip()
                ln = str(r.get("Last Name","")).strip()
                name_str = f'{fn} {ln}'.strip() or '(no name)'
                ph = str(r.get("Office Phone","")).strip() or str(r.get("Mobile Phone","")).strip()
                ph_str = f' [{ph}]' if ph else ''
                em = str(r.get("Primary Email","")).strip()
                em_str = f' <{em}>' if em else ''
                f.write(f'  • {str(r["Company"])[:55]:<55} → {name_str[:25]:<25} ({str(r["Designation"])[:20]}){ph_str}{em_str}\n')
                if cat in ('CALL_SWITCHBOARD', 'MCA_LOOKUP'):
                    f.write(f'      ACTION: {action}\n')
            f.write('\n')
