"""
build_vtiger_file.py
====================
Takes a list of companies + per-company enrichment dicts and writes the final
Vtiger-ready files (XLSX + comma-CSV + coverage report).

This script runs in Claude.ai's analysis tool (Python sandbox). It uses only
pandas and openpyxl — both pre-installed. Web enrichment is done by Claude
BEFORE calling this script (via WebSearch / WebFetch); this script just formats.

USAGE (from within a Claude analysis tool block):
    from build_vtiger_file import build_files

    companies = [
        {"EnterpriseName": "ACME LIMITED", "Address": "...", "State": "...",
         "District": "MUMBAI", "Pincode": "400001"},
        ...
    ]
    enrichment = {
        "ACME LIMITED": {
            "first": "Anil", "last": "Kumar", "designation": "CIO",
            "email": "anil@acme.com", "phone": "022-12345678", "mobile": "",
            "website": "https://acme.com", "linkedin": "https://linkedin.com/in/anilkumar",
            "source_url": "https://www.zaubacorp.com/company/ACME-LIMITED",
            "confidence": "High", "cin": "L12345MH2000PLC123456",
            "notes": "Verified via company press release",
        },
        ...
    }
    paths = build_files(companies, enrichment, output_dir="/mnt/user-data/outputs")
    # Returns: {"xlsx": "...", "csv": "...", "report": "..."}
"""
import csv
import re
from datetime import date
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font

# ----- 75-column Vtiger schema (exact order) -----
VTIGER_HEADERS = [
    'Lead ID','Company','Salutation','First Name','Last Name','Primary Email',
    'Designation','Location','Industry','Lead Generated on','Lead Generated By',
    'Lead Source','Lead Sub-Status','Lead Status','Office Phone','Created By',
    'Website','Mobile Phone','No. of Branches','Annual Revenue','Last Follow-up On',
    'Number of Employees','Created Time','Next follow-up on','Network Budget',
    'Modified Time','Requirement','Estimated Order Value','CreatedByExt',
    'Assigned To','ModifiedByExt','Record Currency','Last Modified By',
    'Record Conversion Rate','Source Campaign','Last Contacted Via',
    'Reason for Enquiry Lost','Request count','Lead Handled by',
    'Email Confirmation Last requested on','Email Opt-in','IT Users',
    'Primary Phone Field','Primary Email Field','Is closed?','Source',
    'Twitter Username','Engagement Score','Language','Timezone',
    'Facebook Lead ID','Ad Group','SMS opt-in','Fax','Platform','Country',
    'Street','PO Box','Postal Code','City','State','Latitude','Longitude',
    'Additional Details','Lead Image','Consent requested','Data erasure request',
    'Erased','Stop processing request','Track my email engagement',
    'Track my document engagement','Consent Last Requested Time','Facebook Id',
    'Instagram Id','Twitter Id',
]

CITY_FIXES = {
    'NAVI MUMBAI': 'Navi Mumbai', 'MUMBAI CITY': 'Mumbai',
    'KALYAN EAST': 'Kalyan', 'KALYAN': 'Kalyan',
    'BYCULLA': 'Byculla', 'TITWALA': 'Titwala',
    'PUNE': 'Pune', 'MUMBAI': 'Mumbai', 'THANE': 'Thane',
    'PAWANE': 'Navi Mumbai', 'WORLI': 'Mumbai',
    'VIKHROLI': 'Mumbai', 'BELAPUR': 'Navi Mumbai',
}

COMMON_FEMALE = {
    'priya','neha','pooja','reema','riya','asha','sneha','meera','radha',
    'sunita','geeta','seema','anita','kavita','smita','rekha','shilpa',
    'swati','ritu','divya','jyoti','rashmi','suman','nisha','manisha',
    'kiran','deepa','preeti','rachna','vandana','aarti','pallavi',
}

def _city(d):
    if not d or pd.isna(d):
        return ''
    return CITY_FIXES.get(str(d).strip().upper(), str(d).strip().title())

def _salutation(first):
    f = (first or '').strip().lower()
    if not f: return ''
    if f in COMMON_FEMALE: return 'Ms.'
    # Heuristic: many Indian female names end in 'a' or 'i'
    if (f.endswith('a') or f.endswith('i')) and f not in {'krishna','vishnu','aditya','akash','manish','rajesh','suresh','ramesh','dinesh','prakash','ashish','satish','jatin'}:
        return 'Ms.'
    return 'Mr.'

def _map_designation(found):
    """Map free-text title to one of AIPL's 4 target buckets. Word-boundary safe."""
    if not found:
        return ('IT Manager / IT Head', False, True)  # default placeholder for blank
    f = found.strip()
    fl = f.lower()
    if re.search(r'\b(cio|cto|ciso|chief\s+information\s+officer|chief\s+technology\s+officer|vp\s*-?\s*(it|tech|technology|information)|vice\s*president\s*-?\s*(it|tech|technology|information))\b', fl):
        return ('VP IT / CISO / CTO', True, False)
    if re.search(r'\b(it\s*infra|infrastructure\s*(head|manager|lead))\b', fl):
        return ('IT Infra / Sr. IT Infra', True, False)
    if re.search(r'\b(it\s*(procurement|purchase|purchasing)|procurement\s*head|purchase\s*head)\b', fl):
        return ('IT Procurement / Purchase', True, False)
    if re.search(r'\b(it\s*(head|manager|lead)|head\s*-?\s*it|head\s+of\s+(it|technology|digital)|manager\s*-?\s*it|sr\.?\s*vp\s*&?\s*cio)\b', fl):
        return ('IT Manager / IT Head', True, False)
    # Non-IT title — keep verbatim, flag as gatekeeper
    return (f, False, False)

def _build_row(src, enr):
    """Build one Vtiger row from a source company dict + enrichment dict."""
    row = {h: '' for h in VTIGER_HEADERS}

    # ---- Defaults (apply to every row) ----
    row['Lead Generated on']      = date.today().strftime('%d/%m/%Y')
    row['Lead Source']            = 'Master DB'
    row['Lead Sub-Status']        = 'Not Connected'
    row['Lead Status']            = 'Prospect'
    row['Record Currency']        = 'INR'
    row['Record Conversion Rate'] = '1'
    row['Request count']          = '0'
    row['Email Opt-in']           = 'singleoptinuser'
    row['SMS opt-in']             = 'singleoptinuser'
    row['Is closed?']             = 'No'
    row['Source']                 = 'IMPORT'
    row['Engagement Score']       = '0'
    row['Country']                = 'India'

    # ---- Source address fields ----
    row['Company'] = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
    row['Street']  = str(src.get('Address') or '').strip()
    pin = src.get('Pincode') or src.get('Postal Code') or ''
    if pin and not pd.isna(pin):
        row['Postal Code'] = str(int(pin)) if isinstance(pin, (int, float)) else str(pin).strip()
    row['City']    = _city(src.get('District') or src.get('City'))
    row['State']   = str(src.get('State') or 'Maharashtra').title()

    # ---- Enrichment fields ----
    enr = enr or {}
    fn = (enr.get('first') or '').strip()
    ln = (enr.get('last') or '').strip()
    found_title = (enr.get('designation') or '').strip()
    mapped_title, is_it_role, is_default = _map_designation(found_title)

    row['Salutation']    = _salutation(fn) if fn else ''
    row['First Name']    = fn
    row['Last Name']     = ln
    row['Designation']   = mapped_title
    row['Primary Email'] = (enr.get('email') or '').strip()
    row['Office Phone']  = (enr.get('phone') or '').strip()
    row['Mobile Phone']  = (enr.get('mobile') or '').strip()
    row['Website']       = (enr.get('website') or '').strip()

    # ---- Additional Details: stash provenance ----
    details = []
    if (fn or ln) and not is_it_role and found_title:
        details.append('ROLE FLAG: Not IT-specific — use as gatekeeper to reach IT decision-maker')
    cin = (enr.get('cin') or '').strip()
    linkedin = (enr.get('linkedin') or '').strip()
    source_url = (enr.get('source_url') or '').strip()
    confidence = (enr.get('confidence') or '').strip()
    notes = (enr.get('notes') or '').strip()
    if cin:        details.append(f'CIN: {cin}')
    if linkedin:   details.append(f'LinkedIn: {linkedin}')
    if source_url: details.append(f'Source: {source_url}')
    if confidence: details.append(f'Confidence: {confidence}')
    if notes:      details.append(f'Notes: {notes}')
    row['Additional Details'] = ' | '.join(details)
    return row

def build_files(companies, enrichment, output_dir='/mnt/user-data/outputs', filename_base='Hygienic_Leads'):
    """
    Build all three output files.

    companies: list of dicts with at least EnterpriseName/Company + address fields
    enrichment: dict keyed by company name -> enrichment dict
                {first, last, designation, email, phone, mobile, website,
                 linkedin, source_url, confidence, cin, notes}
    output_dir: where to write the files (Claude analysis tool default works)
    filename_base: base filename (default "Hygienic_Leads")

    Returns dict of paths: {"xlsx", "csv", "report"}
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    xlsx_path = out_dir / f'{filename_base}.xlsx'
    csv_path  = out_dir / f'{filename_base}.csv'
    rpt_path  = out_dir / f'{filename_base}_Coverage_Report.txt'

    rows = []
    for src in companies:
        key = str(src.get('EnterpriseName') or src.get('Company') or '').strip()
        enr = enrichment.get(key, {})
        rows.append(_build_row(src, enr))

    # ---- XLSX (for human review) ----
    wb = Workbook()
    ws = wb.active
    ws.title = 'Vtiger_Leads'
    ws.append(VTIGER_HEADERS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    for r in rows:
        ws.append([r[h] for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws.cell(row=1, column=ci).column_letter
        ws.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws.freeze_panes = 'A2'
    wb.save(xlsx_path)

    # ---- Comma-CSV (for Vtiger import) ----
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

    # ---- Coverage report (plain text for the team) ----
    n = len(rows)
    named   = sum(1 for r in rows if r['First Name'] or r['Last Name'])
    emails  = sum(1 for r in rows if r['Primary Email'])
    phones  = sum(1 for r in rows if r['Office Phone'] or r['Mobile Phone'])
    sites   = sum(1 for r in rows if r['Website'])
    it_role = sum(1 for r in rows if r['Designation'] in {
        'VP IT / CISO / CTO','IT Manager / IT Head',
        'IT Infra / Sr. IT Infra','IT Procurement / Purchase'
    } and (r['First Name'] or r['Last Name']))
    gatekeepers = sum(1 for r in rows if 'ROLE FLAG' in r['Additional Details'])
    blanks = [r['Company'] for r in rows if not (r['First Name'] or r['Last Name'])]

    with open(rpt_path, 'w', encoding='utf-8') as f:
        f.write('AIPL Lead Enrichment — Coverage Report\n')
        f.write(f'Generated: {date.today().strftime("%d %b %Y")}\n')
        f.write('=' * 60 + '\n\n')
        f.write(f'Total companies:               {n}\n')
        f.write(f'Named contacts found:          {named}  ({100*named//n if n else 0}%)\n')
        f.write(f'  - IT-specific (CIO/IT Head): {it_role}\n')
        f.write(f'  - Gatekeepers (MD/Director): {gatekeepers}\n')
        f.write(f'With email:                    {emails}\n')
        f.write(f'With phone (office or mobile): {phones}\n')
        f.write(f'With website:                  {sites}\n\n')
        f.write(f'Still blank ({len(blanks)} companies):\n')
        for b in blanks:
            f.write(f'  - {b}\n')
        if blanks:
            f.write('\nFor blanks: run Mode B to get a prioritized lookup queue for your\n')
            f.write('Lusha/Apollo/Signal Hire/Contact Out credits.\n')

    return {'xlsx': str(xlsx_path), 'csv': str(csv_path), 'report': str(rpt_path)}
