"""
merge_tool_exports.py
=====================
Takes the current master Vtiger file + one or more CSV/XLSX exports from
Lusha / Apollo / Signal Hire / Contact Out, and merges the new contact data
into the master WITHOUT overwriting verified non-empty fields.

Auto-detects which tool each export is from by column signature.

USAGE (from Claude analysis tool):
    from merge_tool_exports import merge_exports

    new_master_path = merge_exports(
        master_file='/mnt/user-data/uploads/Hygienic_Leads.xlsx',
        export_files=['/mnt/user-data/uploads/lusha_export.csv',
                      '/mnt/user-data/uploads/apollo_export.csv'],
        output_dir='/mnt/user-data/outputs',
    )
"""
import csv
import re
from datetime import date
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font

# Import VTIGER_HEADERS from sibling script (or duplicate; safer to duplicate
# for analysis-tool sandbox use where sys.path may not be flexible)
VTIGER_HEADERS = [
    'Lead ID','Company','Salutation','First Name','Last Name','Primary Email',
    'Designation','Location','Industry','Lead Generated on','Lead Generated By',
    'Lead Source','Lead Sub-Status','Lead Status','Office Phone','Created By',
    'Website','Mobile Phone','No. of Branches','Annual Revenue','Last Follow-up On',
    'Number of Employees','Created Time','Next follow-up on','Network Budget',
    'Modified Time','Requirement','Estimated Order Value','CreatedByExt',
    'Assigned To','ModifiedByExt','Record Currency','Last Modified By',
    'Record Conversion Rate','Source Campaign','Last Contacted Via',
    'Reason for Enquiry Lost','Request count','Lead Handled by',
    'Email Confirmation Last requested on','Email Opt-in','IT Users',
    'Primary Phone Field','Primary Email Field','Is closed?','Source',
    'Twitter Username','Engagement Score','Language','Timezone',
    'Facebook Lead ID','Ad Group','SMS opt-in','Fax','Platform','Country',
    'Street','PO Box','Postal Code','City','State','Latitude','Longitude',
    'Additional Details','Lead Image','Consent requested','Data erasure request',
    'Erased','Stop processing request','Track my email engagement',
    'Track my document engagement','Consent Last Requested Time','Facebook Id',
    'Instagram Id','Twitter Id',
]

def _normalize_company(name):
    """Strip common Indian company suffixes for fuzzy matching."""
    if not name: return ''
    n = str(name).upper().strip()
    for suffix in ['M/S ', 'PRIVATE LIMITED', 'PVT LTD', 'PVT. LTD',
                   'PVT LIMITED', 'LIMITED', ' LTD', 'LIABILITY PARTNERSHIP', ' LLP',
                   '(INDIA)', '.', ',']:
        n = n.replace(suffix, ' ')
    return re.sub(r'\s+', ' ', n).strip()

def _detect_tool(df):
    """Identify which paid tool an export CSV came from based on column names."""
    cols = {str(c).lower().strip() for c in df.columns}
    if 'linkedin url' in cols and ('phone' in cols or 'mobile phone' in cols):
        if 'corporate phone' in cols or 'organization name' in cols:
            return 'Apollo'
        return 'Lusha'
    if 'organization name' in cols or 'corporate phone' in cols:
        return 'Apollo'
    if 'personal email' in cols or any(c.startswith('personal') for c in cols):
        return 'Contact Out'
    if any(c in cols for c in ['email 1', 'phone 1', 'full name']):
        return 'Signal Hire'
    if 'company' in cols and 'email' in cols and 'phone' in cols:
        return 'Lusha'
    return 'Unknown'

def _extract_from_export(df, tool_name):
    """Normalize one tool's export rows to a common contact dict format."""
    # Build a column-name lookup (case insensitive)
    col_lower = {str(c).lower().strip(): c for c in df.columns}

    def pick(*names):
        for n in names:
            if n in col_lower:
                return col_lower[n]
        return None

    out = []
    for _, r in df.iterrows():
        # Common name fields by tool
        first_col = pick('first name', 'firstname', 'first')
        last_col  = pick('last name', 'lastname', 'last')
        full_col  = pick('full name', 'name')
        title_col = pick('title', 'position', 'designation', 'job title')
        email_col = pick('email', 'email 1', 'work email', 'business email')
        peml_col  = pick('personal email', 'email 2')
        phone_col = pick('phone', 'work phone', 'corporate phone', 'phone 1', 'office phone')
        mob_col   = pick('mobile', 'mobile phone', 'cell', 'phone 2', 'direct phone')
        comp_col  = pick('company', 'organization name', 'company name', 'organization')
        li_col    = pick('linkedin url', 'linkedin', 'linkedin profile')

        # Split full name if first/last not provided
        if first_col and last_col:
            first = str(r.get(first_col, '') or '').strip()
            last  = str(r.get(last_col, '') or '').strip()
        elif full_col:
            full = str(r.get(full_col, '') or '').strip().split(' ', 1)
            first = full[0] if full else ''
            last  = full[1] if len(full) > 1 else ''
        else:
            first = last = ''

        contact = {
            'first':      first,
            'last':       last,
            'designation': str(r.get(title_col, '') or '').strip() if title_col else '',
            'email':      str(r.get(email_col, '') or '').strip() if email_col else '',
            'mobile':     str(r.get(mob_col, '') or '').strip() if mob_col else '',
            'phone':      str(r.get(phone_col, '') or '').strip() if phone_col else '',
            'linkedin':   str(r.get(li_col, '') or '').strip() if li_col else '',
            'company':    str(r.get(comp_col, '') or '').strip() if comp_col else '',
            'tool':       tool_name,
        }
        # Fallback personal email if work email empty
        if not contact['email'] and peml_col:
            contact['email'] = str(r.get(peml_col, '') or '').strip()
        out.append(contact)
    return out

def merge_exports(master_file, export_files, output_dir='/mnt/user-data/outputs',
                  filename_base='Hygienic_Leads_Updated'):
    """
    Merge tool exports into the master Vtiger file.

    master_file: path to current master XLSX
    export_files: list of paths to tool export CSVs/XLSXs
    output_dir: where to write outputs
    filename_base: base name for new master

    Returns: dict of paths {"xlsx", "csv", "report", "tools_detected": [...]}
    """
    master = pd.read_excel(master_file).fillna('')

    # Index master by normalized company name
    master['_norm'] = master['Company'].apply(_normalize_company)
    master_by_norm = {n: i for i, n in master['_norm'].items()}

    # Load + classify all exports
    all_contacts = []
    tools_detected = []
    for ep in export_files:
        ep = Path(ep)
        if ep.suffix.lower() == '.csv':
            edf = pd.read_csv(ep).fillna('')
        else:
            edf = pd.read_excel(ep).fillna('')
        tool = _detect_tool(edf)
        tools_detected.append({'file': ep.name, 'tool': tool, 'rows': len(edf)})
        contacts = _extract_from_export(edf, tool)
        all_contacts.extend(contacts)

    # Merge: for each export contact, find matching master row by normalized company
    updated_count = 0
    new_rows = []
    skipped = []
    for c in all_contacts:
        if not c['company']:
            skipped.append((c, 'no company name in export'))
            continue
        ckey = _normalize_company(c['company'])
        if ckey not in master_by_norm:
            # No match — could append as new row if address known, else skip
            skipped.append((c, f"no matching company in master: {c['company']}"))
            continue
        ridx = master_by_norm[ckey]
        # Backfill empties only — never overwrite verified data
        mapping = {
            'First Name':   c['first'],
            'Last Name':    c['last'],
            'Designation':  c['designation'],
            'Primary Email': c['email'],
            'Office Phone': c['phone'],
            'Mobile Phone': c['mobile'],
        }
        changed = False
        for col, new_val in mapping.items():
            if new_val and not str(master.at[ridx, col]).strip():
                master.at[ridx, col] = new_val
                changed = True
        # Always append the tool tag + LinkedIn to Additional Details
        ad = str(master.at[ridx, 'Additional Details'])
        new_bits = []
        if c['linkedin'] and 'LinkedIn:' not in ad:
            new_bits.append(f"LinkedIn: {c['linkedin']}")
        new_bits.append(f"Source: {c['tool']} (manual unlock)")
        new_bits.append('Confidence: High')
        master.at[ridx, 'Additional Details'] = (ad + (' | ' if ad else '') + ' | '.join(new_bits)).strip(' |')
        if changed:
            updated_count += 1

    master = master.drop(columns=['_norm'])

    # Write outputs
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    xlsx_path = out_dir / f'{filename_base}.xlsx'
    csv_path  = out_dir / f'{filename_base}.csv'
    rpt_path  = out_dir / f'{filename_base}_Merge_Report.txt'

    wb = Workbook()
    ws = wb.active
    ws.title = 'Vtiger_Leads'
    ws.append(VTIGER_HEADERS)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    for _, r in master.iterrows():
        ws.append([r.get(h, '') for h in VTIGER_HEADERS])
    for ci, h in enumerate(VTIGER_HEADERS, 1):
        col_letter = ws.cell(row=1, column=ci).column_letter
        ws.column_dimensions[col_letter].width = min(max(len(h) + 2, 12), 50)
    ws.freeze_panes = 'A2'
    wb.save(xlsx_path)

    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=VTIGER_HEADERS, delimiter=',', quoting=csv.QUOTE_ALL)
        w.writeheader()
        for _, r in master.iterrows():
            w.writerow({h: r.get(h, '') for h in VTIGER_HEADERS})

    with open(rpt_path, 'w', encoding='utf-8') as f:
        f.write(f'Tool Export Merge Report — {date.today().strftime("%d %b %Y")}\n')
        f.write('='*60 + '\n\n')
        f.write('Exports processed:\n')
        for td in tools_detected:
            f.write(f"  - {td['file']}: detected as {td['tool']} ({td['rows']} rows)\n")
        f.write(f'\nMaster rows updated:  {updated_count}\n')
        f.write(f'Export rows skipped: {len(skipped)}\n')
        if skipped:
            f.write('\nSkipped reasons:\n')
            for c, reason in skipped[:20]:
                f.write(f"  - {c.get('company','?')}: {reason}\n")
            if len(skipped) > 20:
                f.write(f"  ...and {len(skipped)-20} more\n")

    return {
        'xlsx': str(xlsx_path), 'csv': str(csv_path), 'report': str(rpt_path),
        'tools_detected': tools_detected, 'updated': updated_count,
        'skipped': len(skipped),
    }
